### ISSUE TITLE
Problem with cuda.jit  ptx?

### ISSUE THREAD

**Issue by cems2** [numba/numba#3794]
**I resolved my problem reported below by downgrading to cudatoolkit=9.0
I still don't understand why this works on one machine with cudatoolkit=10 or cudatoolkit=9.2 using an RTX2080   but fails on another machine using a GTX1080 unless I downgrade to cudatoolkit=9.0

So I'm leaving this bug report here in case someone else is searching for this issue**

_updated information_
this one works only with cudatools = 9.0 but not 9.2 or 10.
GPU:  GTX1080
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |

this one works with cudatools=10
GPU: RTX2070
 NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |

----------------------  Old Now Resolved problem Report --------------------------------

I've installed numba cuda several times in the past with success but now suddenly I cannot get new installs to work.  They all fail with the following error message:
LinkerError: [218] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal   : Unsupported .version 6.3; current version is '6.1'
ptxas fatal   : Ptx assembly aborted due to errors

**Regression:**  
I convinced myself this seems to be a bug not an error on my part by cloning a working conda environment.  The conda environment works on one machines but not on another.  I also just built some conda envs from scratch as well.  ANd finally I tried downgrading from cudatoolkit=10 to cudatoolkit=9.2  
None of these works.

I found discussions of this error online and all of them point to finding the ptx source directory and rebuilding it.  But I cannot locate this source directory in the location these older error reports indicated soI cannot test this.  But since I'm doing an install directly from conda I think that might not be the problem here.

Configuration:
```
uname -v
#39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018
```

**Steps to reproduce**
Here is the full reproducible error.  I am showing this using ipython but it also fails when just run as a command line file.
```
In [13]: @cuda.jit("void(float32[:])")
    ...: def foo(x):
    ...:     x[0]=99
    ...: 
    ...: 
---------------------------------------------------------------------------
CudaAPIError                              Traceback (most recent call last)
~/anaconda3/envs/gpu/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py in add_ptx(self, ptx, name)
   1562             driver.cuLinkAddData(self.handle, enums.CU_JIT_INPUT_PTX,
-> 1563                                  ptxbuf, len(ptx), namebuf, 0, None, None)
   1564         except CudaAPIError as e:

~/anaconda3/envs/gpu/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py in safe_cuda_api_call(*args)
    287             retcode = libfn(*args)
--> 288             self._check_error(fname, retcode)
    289         return safe_cuda_api_call

~/anaconda3/envs/gpu/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py in _check_error(self, fname, retcode)
    322                     raise CudaDriverError("CUDA initialized before forking")
--> 323             raise CudaAPIError(retcode, msg)
    324 

CudaAPIError: [218] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR

During handling of the above exception, another exception occurred:

LinkerError                               Traceback (most recent call last)
<ipython-input-13-80badbc16f7a> in <module>()
----> 1 @cuda.jit("void(float32[:])")
      2 def foo(x):
      3     x[0]=99
      4 

~/anaconda3/envs/gpu/lib/python3.6/site-packages/numba/cuda/decorators.py in kernel_jit(func)
     94             # Force compilation for the current context
     95             if bind:
---> 96                 kernel.bind()
     97 
     98             return kernel

~/anaconda3/envs/gpu/lib/python3.6/site-packages/numba/cuda/compiler.py in bind(self)
    493         Force binding to current CUDA context
    494         """
--> 495         self._func.get()
    496 
    497     @property

~/anaconda3/envs/gpu/lib/python3.6/site-packages/numba/cuda/compiler.py in get(self)
    375             # Link
    376             linker = driver.Linker()
--> 377             linker.add_ptx(ptx)
    378             for path in self.linking:
    379                 linker.add_file_guess_ext(path)

~/anaconda3/envs/gpu/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py in add_ptx(self, ptx, name)
   1563                                  ptxbuf, len(ptx), namebuf, 0, None, None)
   1564         except CudaAPIError as e:
-> 1565             raise LinkerError("%s\n%s" % (e, self.error_log))
   1566 
   1567     def add_file(self, path, kind):

LinkerError: [218] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal   : Unsupported .version 6.3; current version is '6.1'
ptxas fatal   : Ptx assembly aborted due to errors
```

**numba environment**

```
 $ numba -s
System info:
--------------------------------------------------------------------------------
__Time Stamp__
2019-02-22 03:07:23.391771

__Hardware Information__
Machine                             : x86_64
CPU Name                            : skylake
CPU Features                        : 
adx aes avx avx2 bmi bmi2 clflushopt cmov cx16 f16c fma fsgsbase lzcnt mmx movbe
pclmul popcnt prfchw rdrnd rdseed rtm sgx sse sse2 sse3 sse4.1 sse4.2 ssse3
xsave xsavec xsaveopt xsaves

__OS Information__
Platform                            : Linux-4.15.0-36-generic-x86_64-with-debian-stretch-sid
Release                             : 4.15.0-36-generic
System Name                         : Linux
Version                             : #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018
OS specific info                    : debianstretch/sid
glibc info                          : glibc 2.9

__Python Information__
Python Compiler                     : GCC 7.2.0
Python Implementation               : CPython
Python Version                      : 3.6.4
Python Locale                       : en_US UTF-8

__LLVM information__
LLVM version                        : 6.0.0

__CUDA Information__
Found 1 CUDA devices
id 0     b'GeForce GTX 1080'                              [SUPPORTED]
                      compute capability: 6.1
                           pci device id: 0
                              pci bus id: 1
Summary:
	1/1 devices are supported
CUDA driver version                 : 9010
CUDA libraries:
Finding cublas
	named  libcublas.so.10.0.130
	trying to open library...	ok
Finding cusparse
	named  libcusparse.so.10.0.130
	trying to open library...	ok
Finding cufft
	named  libcufft.so.10.0.145
	trying to open library...	ok
Finding curand
	named  libcurand.so.10.0.130
	trying to open library...	ok
Finding nvvm
	named  libnvvm.so.3.3.0
	trying to open library...	ok
	finding libdevice for compute_20...	ok
	finding libdevice for compute_30...	ok
	finding libdevice for compute_35...	ok
	finding libdevice for compute_50...	ok

__SVML Information__
SVML state, config.USING_SVML       : False
SVML library found and loaded       : False
llvmlite using SVML patched LLVM    : True
SVML operational:                   : False

__Conda Information__
conda_build_version                 : 3.0.27
conda_env_version                   : 4.6.4
platform                            : linux-64
python_version                      : 3.6.6.final.0
root_writable                       : True

__Current Conda Env__
absl-py                   0.1.9                    pypi_0    pypi
astor                     0.6.2                    pypi_0    pypi
blas                      1.0                         mkl  
bleach                    1.5.0                    pypi_0    pypi
ca-certificates           2019.1.23                     0  
certifi                   2018.11.29               py36_0  
cudatoolkit               10.0.130                      0  
curl                      7.55.1               h78862de_4  
cycler                    0.10.0           py36h93f1223_0  
dbus                      1.10.22              h3b5a359_0  
decorator                 4.2.1                    py36_0  
entrypoints               0.2.3            py36h1aec115_2  
expat                     2.2.5                he0dffb1_0  
fontconfig                2.12.4               h88586e7_1  
freetype                  2.8                  hab7d2ae_1  
gast                      0.2.0                    pypi_0    pypi
git                       2.15.0          pl526h838b92b_0  
glib                      2.53.6               h5d9569c_2  
gmp                       6.1.2                h6c8ec71_1  
gst-plugins-base          1.12.2               he3457e5_0  
gstreamer                 1.12.2               h4f93127_0  
html5lib                  0.9999999                pypi_0    pypi
icu                       58.2                 h9c2bf20_1  
intel-openmp              2018.0.0             hc7b2577_8  
ipykernel                 4.8.0                    py36_0  
ipython                   6.2.1            py36h88c514a_1  
ipython_genutils          0.2.0            py36hb52b0d5_0  
ipywidgets                7.1.0                    py36_0  
jedi                      0.11.1                   py36_0  
jinja2                    2.10             py36ha16c418_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0            py36h006f8b5_0  
jupyter                   1.0.0            py36h9896ce5_0  
jupyter_client            5.2.2                    py36_0  
jupyter_console           5.2.0            py36he59e554_1  
jupyter_core              4.4.0            py36h7c827e3_0  
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                h7cc24e2_2  
libgfortran-ng            7.2.0                h9f7466a_2  
libpng                    1.6.34               hb9fc6fc_0  
libsodium                 1.0.15               hf101ebd_0  
libssh2                   1.8.0                h9cfc8f7_4  
libstdcxx-ng              7.2.0                h7a57d05_2  
libtiff                   4.0.9                h28f6b97_0  
libxcb                    1.12                 hcd93eb1_4  
libxml2                   2.9.4                h2e8b1d7_6  
llvmlite                  0.24.0           py36hdbcaa40_0  
markdown                  2.6.11                   pypi_0    pypi
markupsafe                1.0              py36hd9260cd_1  
matplotlib                2.1.2            py36h0e671d2_0  
mistune                   0.8.3                    py36_0  
mkl                       2018.0.1             h19d6760_4  
nbconvert                 5.3.1            py36hb41ffb7_0  
nbformat                  4.4.0            py36h31c9010_0  
ncurses                   6.0                  h9df7e31_2  
notebook                  5.3.1                    py36_1  
numba                     0.39.0           py36h04863e7_0  
numpy                     1.14.0           py36h3dfced4_0  
olefile                   0.44             py36h79f9f78_0  
openssl                   1.0.2p               h14c3975_0  
pandoc                    1.19.2.1             hea2e7c5_1  
pandocfilters             1.4.2            py36ha6701b7_1  
parso                     0.1.1            py36h35f843b_0  
pcre                      8.41                 hc27e229_1  
perl                      5.26.0               hae598fd_0  
pexpect                   4.3.1                    py36_0  
pickleshare               0.7.4            py36h63277f8_0  
pillow                    5.0.0            py36h3deb7b8_0  
pip                       9.0.1            py36h6c6f9ce_4  
prompt_toolkit            1.0.15           py36h17d85b1_0  
protobuf                  3.5.1                    pypi_0    pypi
ptyprocess                0.5.2            py36h69acd42_0  
pygments                  2.2.0            py36h0d3125c_0  
pyparsing                 2.2.0            py36hee85983_1  
pyqt                      5.6.0            py36h0386399_5  
python                    3.6.4                hc3d631a_1  
python-dateutil           2.6.1            py36h88d3b88_1  
pytz                      2017.3           py36h63b9c63_0  
pyzmq                     16.0.3           py36he2533c7_0  
qt                        5.6.2               h974d657_12  
qtconsole                 4.3.1            py36h8f73b5b_0  
readline                  7.0                  ha6073c6_4  
scipy                     1.0.0            py36hbf646e7_0  
send2trash                1.4.2                    py36_0  
setuptools                38.4.0                   py36_0  
simplegeneric             0.8.1            py36h2cb9092_0  
sip                       4.18.1           py36h51ed4ed_2  
six                       1.11.0           py36h372c433_1  
sqlite                    3.21.0               h1bed415_0  
tensorflow                1.5.0rc0                 pypi_0    pypi
tensorflow-tensorboard    0.4.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.1                    py36_0  
testpath                  0.3.1            py36h8cadb63_0  
tk                        8.6.7                hc745277_3  
tornado                   4.5.3                    py36_0  
traitlets                 4.3.2            py36h674d592_0  
wcwidth                   0.1.7            py36hdf4376a_0  
webencodings              0.5.1            py36h800622e_1  
werkzeug                  0.14.1                   pypi_0    pypi
wheel                     0.30.0           py36hfd4bba0_1  
widgetsnbextension        3.1.0                    py36_0  
xz                        5.2.3                h55aa19d_2  
zeromq                    4.2.2                hbedb6e5_2  
zlib                      1.2.11               ha838bed_2  
--------------------------------------------------------------------------------
If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.

=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
=============================================================
```

**Conda environment**
I have tried several conda environments that all work on a RTX2080 as well as enviromnents that are currently working on my GTX 1080 but fail when I clone them and run the code.  For example here is an enviroment that I use with tensor flow on a gpu.  it is failing for Numba

```
$ cat tensorflowgpu.yml 
name: gpu
channels:
  - defaults
dependencies:
  - ca-certificates=2017.08.26=h1d4fec5_0
  - certifi=2017.11.5=py36hf29ccca_0
  - curl=7.55.1=h78862de_4
  - cycler=0.10.0=py36h93f1223_0
  - dbus=1.10.22=h3b5a359_0
  - decorator=4.2.1=py36_0
  - entrypoints=0.2.3=py36h1aec115_2
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.12.4=h88586e7_1
  - freetype=2.8=hab7d2ae_1
  - git=2.15.0=pl526h838b92b_0
  - glib=2.53.6=h5d9569c_2
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.12.2=he3457e5_0
  - gstreamer=1.12.2=h4f93127_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2018.0.0=hc7b2577_8
  - ipykernel=4.8.0=py36_0
  - ipython=6.2.1=py36h88c514a_1
  - ipython_genutils=0.2.0=py36hb52b0d5_0
  - ipywidgets=7.1.0=py36_0
  - jedi=0.11.1=py36_0
  - jinja2=2.10=py36ha16c418_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py36h006f8b5_0
  - jupyter=1.0.0=py36h9896ce5_0
  - jupyter_client=5.2.2=py36_0
  - jupyter_console=5.2.0=py36he59e554_1
  - jupyter_core=4.4.0=py36h7c827e3_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=h7cc24e2_2
  - libgfortran-ng=7.2.0=h9f7466a_2
  - libpng=1.6.34=hb9fc6fc_0
  - libsodium=1.0.15=hf101ebd_0
  - libssh2=1.8.0=h9cfc8f7_4
  - libstdcxx-ng=7.2.0=h7a57d05_2
  - libtiff=4.0.9=h28f6b97_0
  - libxcb=1.12=hcd93eb1_4
  - libxml2=2.9.4=h2e8b1d7_6
  - markupsafe=1.0=py36hd9260cd_1
  - matplotlib=2.1.2=py36h0e671d2_0
  - mistune=0.8.3=py36_0
  - mkl=2018.0.1=h19d6760_4
  - nbconvert=5.3.1=py36hb41ffb7_0
  - nbformat=4.4.0=py36h31c9010_0
  - ncurses=6.0=h9df7e31_2
  - notebook=5.3.1=py36_1
  - numpy=1.14.0=py36h3dfced4_0
  - olefile=0.44=py36h79f9f78_0
  - openssl=1.0.2n=hb7f436b_0
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py36ha6701b7_1
  - parso=0.1.1=py36h35f843b_0
  - pcre=8.41=hc27e229_1
  - perl=5.26.0=hae598fd_0
  - pexpect=4.3.1=py36_0
  - pickleshare=0.7.4=py36h63277f8_0
  - pillow=5.0.0=py36h3deb7b8_0
  - pip=9.0.1=py36h6c6f9ce_4
  - prompt_toolkit=1.0.15=py36h17d85b1_0
  - ptyprocess=0.5.2=py36h69acd42_0
  - pygments=2.2.0=py36h0d3125c_0
  - pyparsing=2.2.0=py36hee85983_1
  - pyqt=5.6.0=py36h0386399_5
  - python=3.6.4=hc3d631a_1
  - python-dateutil=2.6.1=py36h88d3b88_1
  - pytz=2017.3=py36h63b9c63_0
  - pyzmq=16.0.3=py36he2533c7_0
  - qt=5.6.2=h974d657_12
  - qtconsole=4.3.1=py36h8f73b5b_0
  - readline=7.0=ha6073c6_4
  - scipy=1.0.0=py36hbf646e7_0
  - send2trash=1.4.2=py36_0
  - setuptools=38.4.0=py36_0
  - simplegeneric=0.8.1=py36h2cb9092_0
  - sip=4.18.1=py36h51ed4ed_2
  - six=1.11.0=py36h372c433_1
  - sqlite=3.21.0=h1bed415_0
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36h8cadb63_0
  - tk=8.6.7=hc745277_3
  - tornado=4.5.3=py36_0
  - traitlets=4.3.2=py36h674d592_0
  - wcwidth=0.1.7=py36hdf4376a_0
  - webencodings=0.5.1=py36h800622e_1
  - wheel=0.30.0=py36hfd4bba0_1
  - widgetsnbextension=3.1.0=py36_0
  - xz=5.2.3=h55aa19d_2
  - zeromq=4.2.2=hbedb6e5_2
  - zlib=1.2.11=ha838bed_2
  - pip:
    - absl-py==0.1.9
    - astor==0.6.2
    - bleach==1.5.0
    - gast==0.2.0
    - html5lib==0.9999999
    - markdown==2.6.11
    - protobuf==3.5.1
    - tensorflow==1.5.0rc0
    - tensorflow-tensorboard==0.4.0
    - termcolor==1.1.0
    - werkzeug==0.14.1

```

**Comment by cems2** [comment]
here is another conda environment that works on an RTX2080 but is failing when I try to clone it to a GTX1080 machine.  THis enviroment isn't set up for tensorflow so might be simpler to reproduce for someone 
```
 cat shallowwater.yml
name: shallowwater
channels:
  - numba
  - defaults
dependencies:
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2018.12.5=0
  - certifi=2018.11.29=py37_0
  - cftime=1.0.3.4=py37hdd07704_0
  - cudatoolkit=10.0.130=0
  - cupy=5.1.0=py37hc0ce245_0
  - curl=7.63.0=hbc83047_1000
  - cycler=0.10.0=py37_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.3.0=py37_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - fastrlock=0.4=py37he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.2.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.4.2=py37_0
  - jedi=0.13.2=py37_0
  - jinja2=2.10=py37_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.4.0=py37_0
  - kiwisolver=1.0.1=py37hf484d3e_0
  - krb5=1.16.1=h173b8e3_7
  - libcurl=7.63.0=h20c2e04_1000
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libnetcdf=4.6.1=h11d0813_2
  - libpng=1.6.36=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.8.0=h1ba5d50_4
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - llvmlite=0.27.0=py37hd408876_0
  - markupsafe=1.1.0=py37h7b6447c_0
  - matplotlib=3.0.2=py37h5429711_0
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - nbconvert=5.3.1=py37_0
  - nbformat=4.4.0=py37_0
  - nccl=1.3.5=cuda10.0_0
  - ncurses=6.1=he6710b0_1
  - netcdf4=1.4.2=py37h808af73_0
  - notebook=5.7.4=py37_0
  - numba=0.42.0=py37h962f231_0
  - numpy=1.15.4=py37h7e9f1db_0
  - numpy-base=1.15.4=py37hde5b4d6_0
  - openssl=1.1.1a=h7b6447c_0
  - pandas=0.24.0=py37he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.3.1=py37_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=18.1=py37_0
  - prometheus_client=0.5.0=py37_0
  - prompt_toolkit=2.0.7=py37_0
  - ptyprocess=0.6.0=py37_0
  - pygments=2.3.1=py37_0
  - pyparsing=2.3.1=py37_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.2=h0371630_0
  - python-dateutil=2.7.5=py37_0
  - pytz=2018.9=py37_0
  - pyzmq=17.1.2=py37h14c3975_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.4.3=py37_0
  - readline=7.0=h7b6447c_5
  - send2trash=1.5.0=py37_0
  - setuptools=40.6.3=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.26.0=h7b6447c_0
  - terminado=0.8.1=py37_1
  - testpath=0.4.2=py37_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py37h7b6447c_0
  - traitlets=4.3.2=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.32.3=py37_0
  - widgetsnbextension=3.4.2=py37_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=h7b6447c_3
  - icc_rt=2018.0.2=0
prefix: /home/rrs/anaconda3/envs/shallowwater
```

**Comment by cems2** [comment]
Solved by downgrading to cudatoolkit=9.0

**Comment by stuartarchibald** [comment]
Are the driver versions the same on both machines?

**Comment by cems2** [comment]
Stuart could you clarify for me what you mean by Driver versions.  Maybe you are referring to something outside of the Anaconda Numba install libs. Perhaps some nvidia libs?  The term Driver is generic to me.  These are different Nvidia Cards RTX2070 and GTX1080 on different (mint) linux computers.

**Comment by stuartarchibald** [comment]
The `nvidia-smi` command show you the driver version installed, this is not something Anaconda supplies or handles as it is system wide. Example:
```
$ nvidia-smi 
<date>
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.93       Driver Version: 410.93       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
```

**Comment by cems2** [comment]
_updated information_
this one works only with cudatools = 9.0 but not 9.2 or 10.
GPU:  GTX1080
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |

this one works with cudatools=10
GPU: RTX2070
 NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |

**Comment by stuartarchibald** [comment]
Please see `Table 1. CUDA Toolkit and Compatible Driver Versions` of the Release Notes https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html,  this should help explain what you are seeing. Thanks.

**Comment by cems2** [comment]
thank you.

**Comment by stuartarchibald** [comment]
No problem, think this now resolved with a suitable explanation. Thanks for your patience in diagnosing the issue. Closing.
