### ISSUE TITLE
"Call to cuPointerGetAttribute" errors with multi-process + multi-GPU + external GPU arrays

### ISSUE THREAD

**Issue by leofang** [numba/numba#4745]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

So far in every GPU Hackathon I attended my teams can always spot one or two bugs 😆 

But this one is particularly pathological and hard to catch. It requires 3 conditions:
1. Running on a node with multiple GPUs
2. In a multi-process environment (we use MPI here, but no need to do any MPI communications); each process controls 1 GPU
3. The input array is from a 3rd-party GPU library that supports `__cuda_array_interface__` ***and*** manages its own CUDA context (so can't just fake a `GPUarray` instance to test this)

Relaxing some of the conditions would either make it run correctly, or is not tested.

MWE:
```python
import math
import numpy as np

from mpi4py import MPI    # mpi is initialized here
comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

import cupy as cp
cp.cuda.Device(rank).use()  # set device based on rank, a cuda context is initialized here
from numba import cuda

@cuda.jit
def just_a_cosine(arr):
    x = cuda.grid(1)
    if x < arr.size:
        arr[x] = math.cos(arr[x])

arr = cp.random.random((10,), dtype=np.float32)
just_a_cosine[(1,), (10,)](arr)  # <----error with N>=2 processes
```

Output:
```shell
leofang@somewhere:~/test$ mpirun -n 2 python -u test_numba_innerloop3.py
Traceback (most recent call last):
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/typing/context.py", line 344, in resolve_argument_type
    return typeof(val, Purpose.argument)
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/typing/typeof.py", line 34, in typeof
    raise ValueError(msg)
ValueError: cannot determine Numba type of <class 'cupy.core.core.ndarray'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_numba_innerloop3.py", line 20, in <module>
    just_a_cosine[(1,), (10,)](arr)  # <----error with N>=2 processes
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/cuda/compiler.py", line 765, in __call__
    kernel = self.specialize(*args)
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/cuda/compiler.py", line 775, in specialize
    [self.typingctx.resolve_argument_type(a) for a in args])
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/cuda/compiler.py", line 775, in <listcomp>
    [self.typingctx.resolve_argument_type(a) for a in args])
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/typing/context.py", line 347, in resolve_argument_type
    return typeof(numba.cuda.as_cuda_array(val), Purpose.argument)
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/cuda/api.py", line 60, in as_cuda_array
    owner=obj)
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/cuda/cudadrv/devices.py", line 212, in _require_cuda_context
    return fn(*args, **kws)
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/cuda/api.py", line 41, in from_cuda_array_interface
    devptr = driver.get_devptr_for_active_ctx(desc['data'][0])
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 1689, in get_devptr_for_active_ctx
    driver.cuPointerGetAttribute(byref(devptr), attr, ptr)
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 290, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 325, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuPointerGetAttribute results in CUDA_ERROR_INVALID_VALUE
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[897,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

Note that for single process it works correctly. The versions of Numba, CuPy, `__cuda_array_interface__`, CUDA toolkit, Python, etc, are all irrelevant, so is the underlying MPI implementation (tested with Spectrum MPI and Open MPI). 

As mentioned this bug is hard to hit, so when we realized how to reproduce it, getting around it is pretty easy. Still, it's worth reporting such a corner case. I suspect the fix to #4092 might be incomplete...

cc: @jqyin, @dxm447

**Comment by leofang** [comment]
Actually we don't need to call the jit kernel here; removing it and calling `as_cuda_array()` would also reproduce the error:
```python
# ...omitted, see the MWE above

arr = cp.random.random((10,), dtype=np.float32)
arr = cuda.as_cuda_array(arr)
```

**Comment by leofang** [comment]
I am sorry, I don't think this is a valid MWE. Let me close this issue first, and make a better one. Thanks.

**Comment by stuartarchibald** [comment]
@leofang thanks, if you have a MWE for the issue you see that'd be great!

**Comment by leofang** [comment]
@stuartarchibald Thanks. Turns out that this was a false alarm due to multiple mistakes we made. Everything works fine.
