### ISSUE TITLE
Cuda runtime errors when starting up numba

### ISSUE THREAD

**Issue by roshambo919** [numba/numba#6561]
- [X ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).

When this is run in a python script:
```
from numba.cuda.cudadrv.runtime import runtime
cudart_version_major = runtime.get_version()[0]  
```
With the following installed with conda:
![image](https://user-images.githubusercontent.com/20426598/101691938-737e3880-3a3d-11eb-9673-ea309f0916b3.png)

![image](https://user-images.githubusercontent.com/20426598/101691911-66614980-3a3d-11eb-857d-97edb3970c65.png)

And the following from nvidia-smi:
![image](https://user-images.githubusercontent.com/20426598/101691958-7bd67380-3a3d-11eb-9fa7-7de0eb018e80.png)

I receive the following error:
![image](https://user-images.githubusercontent.com/20426598/101691999-8b55bc80-3a3d-11eb-80a6-9c2cea2780d2.png)

Is this a compatibility issue or something else?

It is not easy for me to update the nvidia drivers (on a shared server). If it is a driver issue, why? What dependency does numba have on the nvidia drivers?

**Comment by seibert** [comment]
It looks like you have the correct cudatoolkit package installed to go with your NVIDIA driver.  Basically, CUDA requires that the system driver (shown by nvidia-smi) needs to be >= to the CUDA toolkit.  (So cudatoolkits older than the system driver are fine.)

That said, since this is an "unknown" error, it is hard to debug.  Does PyTorch work on the GPU in your environment?

**Comment by seibert** [comment]
One other question: What GPU do you have on that system?  I doubt it is too old to work with CUDA 10, but just wanted to check.

**Comment by roshambo919** [comment]
Understandable that it is difficult to debug. I was running into the same problem, so I wondered if it was a numba thing or my configuration.

Pytorch does work on the GPU. I get:
```
torch.cuda.is_available() 
true
torch.cuda.get_device_name()  
'Quadro RTX 6000' 
```
This is nvidia-smi output
![image](https://user-images.githubusercontent.com/20426598/101698188-15eee980-3a47-11eb-8ac3-8a2f64edcbf7.png)

**Comment by roshambo919** [comment]
Not sure if this is helpful, but when I tried older versions of numba (0.49 and 0.42), I was getting this on a simple example script. Looks like `numba.cuda.cudadrv.runtime` didn't exist back then (as far as I can tell), so I couldn't test the same thing exactly.

![image](https://user-images.githubusercontent.com/20426598/101698394-649c8380-3a47-11eb-9158-7d4416b3b862.png)

**Comment by esc** [comment]
@roshambo919 thanks for submitting this issue. To do some expectation management: our resident CUDA expert @gmarkall is current out-of-office so you may have to wait until January to receive more support on this one.

**Comment by esc** [comment]
Actually, @testhound -- is there something you can perhaps do about this one?

**Comment by testhound** [comment]
> Actually, @testhound -- is there something you can perhaps do about this one?

@esc I have no idea what to do on this one. I'll look into as best I can, but I am not optimistic without input from @gmarkall.

**Comment by esc** [comment]
@testhound no worries at all sir!

**Comment by stuartarchibald** [comment]
@roshambo919 What's the output of `numba -s`? (Feel free to redact anything you don't want to share).

**Comment by roshambo919** [comment]
Thanks all for the quick replies. Here are some updates on my testing:

Nvidia drivers: 410.78

In the original environment where the problems above occurred.
Env-1:
- cudatoolkit=10.0
- cudnn=7.6.4 (not sure if this makes a difference)
- cudatoolkit-dev=10.1 (not sure if this makes a difference) 
- numba=0.51.2
- pytorch=1.3.1=py3.6_cuda10.0.130_cudnn7.6.3_0

I downgraded cudatoolkit to 9.2 in my environment. The above issue was "fixed" and gave expected outputs, but I ran into a later issue:
Env-2:
- cudatoolkit=9.2
- cudnn=7.6.4 (not sure if this makes a difference)
- cudatoolkit-dev=10.1 (not sure if this makes a difference) 
- numba=0.51.2
- pytorch=1.4.0py3.6_cuda9.2.148_cudnn7.6.3_0

![image](https://user-images.githubusercontent.com/20426598/101805358-a9c0c400-3ae0-11eb-93e1-be8573d69d9b.png)


I tried downgrading to 9.0 from there and saw the same problem as with 9.2
Env-3:
- cudatoolkit=9.0
- cudnn=7.6.4 (not sure if this makes a difference)
- cudatoolkit-dev=10.1 (not sure if this makes a difference) 
- numba=0.51.2
- pytorch=1.1.0=py3.6_cuda9.0.176_cudnn7.5.1_0
**same error as in Env-2**



Output of `numba -s` for env-2:
```
System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2020-12-10 12:15:22.163720
UTC start time                                : 2020-12-10 17:15:22.163725
Running time (s)                              : 2.010989

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : cascadelake
CPU Count                                     : 32
Number of accessible CPUs                     : 32
List of accessible CPUs cores                 : 0-31
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 64bit adx aes avx avx2 avx512bw
                                                avx512cd avx512dq avx512f avx512vl
                                                avx512vnni bmi bmi2 clflushopt
                                                clwb cmov cx16 cx8 f16c fma
                                                fsgsbase fxsr invpcid lzcnt mmx
                                                movbe pclmul pku popcnt prfchw
                                                rdrnd rdseed sahf sse sse2 sse3
                                                sse4.1 sse4.2 ssse3 xsave xsavec
                                                xsaveopt xsaves

Memory Total (MB)                             : 192059
Memory Available (MB)                         : 144900

__OS Information__
Platform Name                                 : Linux-4.15.0-1066-oem-x86_64-with-debian-buster-sid
Platform Release                              : 4.15.0-1066-oem
OS Name                                       : Linux
OS Version                                    : #76-Ubuntu SMP Fri Dec 6 12:04:50 UTC 2019
OS Specific Version                           : ?
Libc Version                                  : glibc 2.9

__Python Information__
Python Compiler                               : GCC 7.3.0
Python Implementation                         : CPython
Python Version                                : 3.6.12
Python Locale                                 : en_US.UTF-8

__LLVM Information__
LLVM Version                                  : 10.0.1

__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : 10000
CUDA Detect Output:
Found 2 CUDA devices
id 0      b'Quadro RTX 6000'                              [SUPPORTED]
                      compute capability: 7.5
                           pci device id: 0
                              pci bus id: 115
id 1      b'Quadro RTX 6000'                              [SUPPORTED]
                      compute capability: 7.5
                           pci device id: 0
                              pci bus id: 166
Summary:
	2/2 devices are supported

CUDA Librairies Test Output:
Finding cublas from Conda environment
	named  libcublas.so.9.2.148
	trying to open library...	ok
Finding cusparse from Conda environment
	named  libcusparse.so.9.2.148
	trying to open library...	ok
Finding cufft from Conda environment
	named  libcufft.so.9.2.148
	trying to open library...	ok
Finding curand from Conda environment
	named  libcurand.so.9.2.148
	trying to open library...	ok
Finding nvvm from Conda environment
	named  libnvvm.so.3.3.0
	trying to open library...	ok
Finding cudart from Conda environment
	named  libcudart.so.9.2.148
	trying to open library...	ok
Finding libdevice from Conda environment
	searching for compute_20...	ok
	searching for compute_30...	ok
	searching for compute_35...	ok
	searching for compute_50...	ok


__ROC information__
ROC Available                                 : False
ROC Toolchains                                : None
HSA Agents Count                              : 0
HSA Agents:
None
HSA Discrete GPUs Count                       : 0
HSA Discrete GPUs                             : None

__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : True
+-->TBB imported successfully.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda Build                                   : not installed
Conda Env                                     : 4.9.2
Conda Platform                                : linux-64
Conda Python Version                          : 3.6.12.final.0
Conda Root Writable                           : True

__Installed Packages__
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
blosc                     1.20.1               hd408876_0  
brotli                    1.0.9                he6710b0_2  
brotlipy                  0.7.0           py36h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.12.8            h06a4308_0  
certifi                   2020.12.5        py36h06a4308_0  
cffi                      1.14.4           py36h261ae71_0  
chardet                   3.0.4           py36h06a4308_1003  
charls                    2.1.0                he6710b0_2  
cloudpickle               1.6.0                      py_0  
cmake                     3.18.2               ha30ef3c_0  
conda                     4.9.2            py36h06a4308_0  
conda-package-handling    1.7.2            py36h03888b9_0  
cryptography              3.3              py36h3c74f83_0  
cudatoolkit               9.2                           0  
cudatoolkit-dev           10.1.243             h516909a_3    conda-forge
cudnn                     7.6.4                 cuda9.2_0  
cycler                    0.10.0                   py36_0  
cytoolz                   0.11.0           py36h7b6447c_0  
dask-core                 2.30.0                     py_0  
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2                      py_0  
easydict                  1.9                        py_0    conda-forge
expat                     2.2.10               he6710b0_2  
fire                      0.3.1              pyh9f0ad1d_0    conda-forge
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.4               h5ab3b9f_0  
giflib                    5.1.4                h14c3975_1  
glib                      2.66.1               h92f7085_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb31296c_0  
icu                       58.2                 he6710b0_3  
idna                      2.10                       py_0  
imagecodecs               2020.5.30        py36hfa7d478_2  
imageio                   2.9.0                      py_0  
intel-openmp              2020.2                      254  
iou3d                     0.0.0                    pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
jxrlib                    1.1                  h7b6447c_2  
kiwisolver                1.3.0            py36h2531618_0  
krb5                      1.18.2               h173b8e3_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libaec                    1.0.4                he6710b0_1  
libcurl                   7.71.1               h20c2e04_1  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libllvm10                 10.0.1               hbcb73fb_5  
libpng                    1.6.37               hbc83047_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libuv                     1.40.0               h7b6447c_0  
libwebp                   1.0.1                h8e7db2f_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
libzopfli                 1.0.3                he6710b0_0  
llvmlite                  0.34.0           py36h269e1b5_4  
lz4-c                     1.9.2                heb0550a_3  
matplotlib                3.3.2                         0  
matplotlib-base           3.3.2            py36h817c723_0  
mkl                       2020.2                      256  
mkl-service               2.3.0            py36he8ac12f_0  
mkl_fft                   1.2.0            py36h23d657b_0  
mkl_random                1.1.1            py36h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
networkx                  2.5                        py_0  
ninja                     1.10.2           py36hff7bd54_0  
numba                     0.51.2           py36h0573a6f_1  
numpy                     1.19.2           py36h54aff64_0  
numpy-base                1.19.2           py36hfa32c7d_0  
olefile                   0.46                     py36_0  
openjpeg                  2.3.0                h05c96fa_1  
openssl                   1.1.1i               h27cfd23_0  
pcre                      8.44                 he6710b0_0  
pillow                    8.0.1            py36he98fc37_0  
pip                       20.3.1           py36h06a4308_0  
pointnet2                 0.0.0                    pypi_0    pypi
pycosat                   0.6.3            py36h27cfd23_0  
pycparser                 2.20                       py_2  
pyopenssl                 20.0.0             pyhd3eb1b0_1  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py36h05f1152_2  
pysocks                   1.7.1            py36h06a4308_0  
python                    3.6.12               hcff3b4d_2  
python-dateutil           2.8.1                      py_0  
pytorch                   1.4.0           py3.6_cuda9.2.148_cudnn7.6.3_0    pytorch
pywavelets                1.1.1            py36h7b6447c_2  
pyyaml                    5.3.1            py36h7b6447c_1  
qt                        5.9.7                h5867ecd_1  
readline                  8.0                  h7b6447c_0  
requests                  2.25.0             pyhd3eb1b0_0  
rhash                     1.4.0                h1ba5d50_0  
roipool3d                 0.0.0                    pypi_0    pypi
ruamel_yaml               0.15.87          py36h7b6447c_1  
scikit-image              0.17.2           py36hdf5156a_0  
scipy                     1.5.2            py36h0b6359f_0  
setuptools                51.0.0           py36h06a4308_2  
sip                       4.19.8           py36hf484d3e_0  
six                       1.15.0           py36h06a4308_0  
snappy                    1.1.8                he6710b0_0  
sqlite                    3.33.0               h62c20be_0  
tbb                       2020.3               hfd86e86_0  
termcolor                 1.1.0                    py36_1  
tifffile                  2020.12.4          pyhd3eb1b0_0  
tk                        8.6.10               hbc83047_0  
toolz                     0.11.1                     py_0  
torchvision               0.5.0                 py36_cu92    pytorch
tornado                   6.1              py36h27cfd23_0  
tqdm                      4.54.1             pyhd3eb1b0_0  
urllib3                   1.25.11                    py_0  
wheel                     0.36.1             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  

No errors reported.


__Warning log__
Warning (roc): Error initialising ROC: No ROC toolchains found.
Warning (roc): No HSA Agents found, encountered exception when searching: Error at driver init: 
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:
Warning (psutil): psutil cannot be imported. For more accuracy, consider installing it.
```

**Comment by uchytilc** [comment]
PTX ISA version 6.3 is for CUDA toolkit 10.0. To get rid of that error you'll have to go back to 10.0. Here's a table I put together a while ago with the driver/toolkit versions. I haven't updated it with 11.0 yet.

As for the runtime error, if you directly import the runtime like that, has Numba initialized CUDA/the context yet?

	PTX ISA 5.0
		Toolkit: 8.0
		Driver: 361.XX
	PTX ISA 6.0
		Toolkit: 9.0
		Driver: 384.XX
		PTX ISA 6.1
		Toolkit: 9.1
		Driver: 387.XX
	PTX ISA 6.2
		Toolkit: 9.2
		Driver: 396.XX
	PTX ISA 6.3
		Toolkit: 10.0
		Driver: 400.XX
	PTX ISA 6.4
		Toolkit: 10.1
		Driver: 418.XX
	PTX ISA 6.5
		Toolkit: 10.2
		Driver: 440.XX

**Comment by roshambo919** [comment]
Hi all - wanted to return to this. Anything else I should try to get this working?

**Comment by gmarkall** [comment]
Hi @roshambo919 - My suspicion is that having both `cudatoolkit` and `cudatoolkit-dev` is causing a problem - I'm wondering if something from cudatoolkit-dev 10.1 is getting picked up and causing the issues you're seeing.

If you try with environments that don't have cudatoolkit-dev installed, do you still observe issues?

**Comment by roshambo919** [comment]
Thanks all for the replies. That would be a good debug step and it'd be interesting to see what happens, but we just had the drivers updated on the machine, and now the same environment is working like a charm.

**Comment by gmarkall** [comment]
Glad to hear it's now working! If there are no outstanding problems, please do close the issue :-)
