### ISSUE TITLE
CudaSupportError: Error at driver init:  [100] Call to cuInit results in CUDA_ERROR_NO_DEVICE:

### ISSUE THREAD

**Issue by torstendahlen** [numba/numba#6777]
Hi,

I'm getting this error when using numba. I have installed rapids.ai on WSL2 with ubuntu 20.04. Rapids GPU packages are working with the GPU. I can load a dataframe into the GPU with cuDF and perform basic calculations with no problem.

However, when I try to use something that requires numba I get this error:
```

from numba import cuda
print(cuda.gpus)

---------------------------------------------------------------------------
CudaAPIError                              Traceback (most recent call last)
~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in initialize(self)
    236             _logger.info('init')
--> 237             self.cuInit(0)
    238         except CudaAPIError as e:

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in safe_cuda_api_call(*args)
    299             retcode = libfn(*args)
--> 300             self._check_error(fname, retcode)
    301         return safe_cuda_api_call

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in _check_error(self, fname, retcode)
    334                     raise CudaDriverError("CUDA initialized before forking")
--> 335             raise CudaAPIError(retcode, msg)
    336 

CudaAPIError: [100] Call to cuInit results in CUDA_ERROR_NO_DEVICE

During handling of the above exception, another exception occurred:

CudaSupportError                          Traceback (most recent call last)
<ipython-input-1-87434641e75b> in <module>
      1 from numba import cuda
----> 2 print(cuda.gpus)

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py in __str__(self)
     41 
     42     def __str__(self):
---> 43         return ', '.join([str(d) for d in self.lst])
     44 
     45     def __iter__(self):

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py in __getattr__(self, attr)
     24             # Device list is not initialized.
     25             # Query all CUDA devices.
---> 26             numdev = driver.get_device_count()
     27             gpus = [_DeviceContextManager(driver.get_device(devid))
     28                     for devid in range(numdev)]

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in get_device_count(self)
    344     def get_device_count(self):
    345         count = c_int()
--> 346         self.cuDeviceGetCount(byref(count))
    347         return count.value
    348 

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in __getattr__(self, fname)
    278         # Initialize driver
    279         if not self.is_initialized:
--> 280             self.initialize()
    281 
    282         if self.initialization_error is not None:

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in initialize(self)
    238         except CudaAPIError as e:
    239             self.initialization_error = e
--> 240             raise CudaSupportError("Error at driver init: \n%s:" % e)
    241         else:
    242             self.pid = _getpid()

CudaSupportError: Error at driver init: 
[100] Call to cuInit results in CUDA_ERROR_NO_DEVICE:
```

When calling %%env there is no
'CUDA_DEVICE_ORDER': , or
 'CUDA_VISIBLE_DEVICES':

If I add these (the RTX 8000 is nr 0):
`import os

os.environ["CUDA_VISIBLE_DEVICES"]="0"`

Still same Error.

I have tested this in numba 0.52.0 and the latest dev with the same issue (0.53.rc2)

**Comment by gmarkall** [comment]
Can you provide the output of:

```
numba -s
```

please?

**Comment by torstendahlen** [comment]
`System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2021-03-01 20:24:02.694366
UTC start time                                : 2021-03-01 19:24:02.694370
Running time (s)                              : 2.639743

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : skylake-avx512
CPU Count                                     : 24
Number of accessible CPUs                     : 24
List of accessible CPUs cores                 : 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 64bit adx aes avx avx2 avx512bw
                                                avx512cd avx512dq avx512f avx512vl
                                                bmi bmi2 clflushopt clwb cmov cx16
                                                cx8 f16c fma fsgsbase fxsr invpcid
                                                lzcnt mmx movbe pclmul popcnt
                                                prfchw rdrnd rdseed rtm sahf sse
                                                sse2 sse3 sse4.1 sse4.2 ssse3
                                                xsave xsavec xsaveopt xsaves

Memory Total (MB)                             : 128677
Memory Available (MB)                         : 127059

__OS Information__
Platform Name                                 : Linux-5.4.91-microsoft-standard-WSL2-x86_64-with-glibc2.10
Platform Release                              : 5.4.91-microsoft-standard-WSL2
OS Name                                       : Linux
OS Version                                    : #1 SMP Mon Jan 25 18:39:31 UTC 2021
OS Specific Version                           : ?
Libc Version                                  : glibc 2.31

__Python Information__
Python Compiler                               : GCC 9.3.0
Python Implementation                         : CPython
Python Version                                : 3.8.8
Python Locale                                 : en_US.UTF-8

__LLVM Information__
LLVM Version                                  : 10.0.1

__CUDA Information__
CUDA Device Initialized                       : False
CUDA Driver Version                           : ?
CUDA Detect Output:
None
CUDA Librairies Test Output:
None

__ROC information__
ROC Available                                 : False
ROC Toolchains                                : None
HSA Agents Count                              : 0
HSA Agents:
None
HSA Discrete GPUs Count                       : 0
HSA Discrete GPUs                             : None

__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : False
+--> Disabled due to Unknown import problem.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda Build                                   : not installed
Conda Env                                     : 4.9.2
Conda Platform                                : linux-64
Conda Python Version                          : 3.8.5.final.0
Conda Root Writable                           : True

__Installed Packages__
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
abseil-cpp                20200225.2           he1b5a44_2    conda-forge
aiohttp                   3.7.4            py38h497a2fe_0    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
anyio                     2.2.0            py38h578d9bd_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               20.1.0           py38h497a2fe_2    conda-forge
arrow-cpp                 1.0.1           py38hcb5322d_14_cuda    conda-forge
arrow-cpp-proc            3.0.0                      cuda    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
aws-c-common              0.4.59               h36c2ea0_1    conda-forge
aws-c-event-stream        0.1.6                had2084c_6    conda-forge
aws-checksums             0.1.10               h4e93380_0    conda-forge
aws-sdk-cpp               1.8.63               h9b98462_0    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
blazingsql                0.18.0                   pypi_0    pypi
bleach                    3.3.0              pyh44b312d_0    conda-forge
bokeh                     2.2.3            py38h578d9bd_0    conda-forge
boost                     1.72.0           py38h1e42940_1    conda-forge
boost-cpp                 1.72.0               h9d3c048_4    conda-forge
brotli                    1.0.9                h9c3ff4c_4    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2021.1.19            h06a4308_0  
cairo                     1.16.0            h7979940_1007    conda-forge
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
cffi                      1.14.5           py38ha65f79e_0    conda-forge
cfitsio                   3.470                hb418390_7    conda-forge
chardet                   4.0.0            py38h578d9bd_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.1              pyhd8ed1ab_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorcet                  2.0.6              pyhd8ed1ab_0    conda-forge
cryptography              3.4.4            py38h3e25421_0    conda-forge
cudatoolkit               11.0.221             h6bb024c_0    nvidia
cudf                      0.18.0          cuda_11.0_py38_g20778e5ddb_0    rapidsai
cudf_kafka                0.18.0          py38_g20778e5ddb_0    rapidsai
cudnn                     8.0.0                cuda11.0_0    nvidia
cugraph                   0.18.0          py38_g65ec965f_0    rapidsai
cuml                      0.18.0          cuda11.0_py38_gb5f59e005_0    rapidsai
cupy                      8.0.0            py38hb7c6141_0    rapidsai
curl                      7.71.1               he644dc0_8    conda-forge
cusignal                  0.18.0          py38_g42899d2_0    rapidsai
cuspatial                 0.18.0          py38_gf4da460_0    rapidsai
custreamz                 0.18.0          py38_g20778e5ddb_0    rapidsai
cuxfilter                 0.18.0          py38_gac6f488_0    rapidsai
cyrus-sasl                2.1.27               h3274739_1    conda-forge
cytoolz                   0.11.0           py38h497a2fe_3    conda-forge
dask                      2021.2.0           pyhd8ed1ab_0    conda-forge
dask-core                 2021.2.0           pyhd8ed1ab_0    conda-forge
dask-cuda                 0.18.0                   py38_0    rapidsai
dask-cudf                 0.18.0          py38_g20778e5ddb_0    rapidsai
datashader                0.11.1             pyh9f0ad1d_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2021.2.0         py38h578d9bd_0    conda-forge
dlpack                    0.3                  he1b5a44_1    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.2.10               h9c3ff4c_0    conda-forge
faiss-proc                1.0.0                      cuda    conda-forge
fastavro                  1.3.2            py38h497a2fe_0    conda-forge
fastrlock                 0.5              py38h709712a_2    conda-forge
fiona                     1.8.18           py38h37fbd03_0    conda-forge
fontconfig                2.13.1            hba837de_1004    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
freexl                    1.0.5             h516909a_1002    conda-forge
fsspec                    0.8.7              pyhd8ed1ab_0    conda-forge
future                    0.18.2           py38h578d9bd_3    conda-forge
gdal                      3.1.4            py38h25844d8_2    conda-forge
geopandas                 0.8.1                      py_0    conda-forge
geos                      3.8.1                he1b5a44_0    conda-forge
geotiff                   1.6.0                h5d11630_3    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glog                      0.4.0                h49b9bf7_3    conda-forge
google-cloud-cpp          1.16.0               he4a878c_2    conda-forge
google-cloud-cpp-common   0.25.0               he83eced_7    conda-forge
googleapis-cpp            0.10.0               h6b1abdc_4    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
grpc-cpp                  1.32.0               h7997a97_1    conda-forge
harfbuzz                  2.7.4                h5cf4720_0    conda-forge
hdf4                      4.2.13            h10796ff_1004    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        3.7.0            py38h578d9bd_0    conda-forge
importlib_metadata        3.7.0                hd8ed1ab_0    conda-forge
ipykernel                 5.5.0            py38h81c977d_1    conda-forge
ipython                   7.21.0           py38h81c977d_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
jedi                      0.18.0           py38h578d9bd_2    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
jpype1                    1.2.1            py38h1fd1430_0    conda-forge
json-c                    0.13.1            hbfbb72e_1002    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter-packaging         0.7.12             pyhd8ed1ab_0    conda-forge
jupyter-server-proxy      1.6.0              pyhd8ed1ab_0    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_core              4.7.1            py38h578d9bd_0    conda-forge
jupyter_server            1.4.1            py38h578d9bd_0    conda-forge
jupyterlab                3.0.9              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.3.0              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
kealib                    1.4.14               he4dc956_1    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcrc32c                 1.1.1                h9c3ff4c_2    conda-forge
libcudf                   0.18.0          cuda11.0_g20778e5ddb_0    rapidsai
libcudf_kafka             0.18.0            g20778e5ddb_0    rapidsai
libcugraph                0.18.0          cuda11.0_g65ec965f_0    rapidsai
libcuml                   0.18.0          cuda11.0_gb5f59e005_0    rapidsai
libcumlprims              0.18.0          cuda11.0_g5939d3e_0    nvidia
libcurl                   7.71.1               hcdd3856_8    conda-forge
libcuspatial              0.18.0          cuda11.0_gf4da460_0    rapidsai
libdap4                   3.20.6               hd7c4107_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libfaiss                  1.6.3           h328c4c8_3_cuda    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgcrypt                 1.8.7                h36c2ea0_0    conda-forge
libgdal                   3.1.4                h02eeb80_2    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libglib                   2.66.7               h1f3bc88_0    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libgpg-error              1.41                 h9c3ff4c_0    conda-forge
libgsasl                  1.8.0                         2    conda-forge
libhwloc                  2.3.0                h5e5b7d1_1    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             hd79254b_1012    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libnetcdf                 4.7.4           nompi_h56d31a8_107    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libntlm                   1.4               h7f98852_1002    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     12.3                 h255efa7_3    conda-forge
libprotobuf               3.13.0.1             h8b12597_0    conda-forge
librdkafka                1.5.3                h54cafa9_0    conda-forge
librmm                    0.18.0          cuda11.0_ga4ee6b7_0    rapidsai
librttopo                 1.1.0                hb271727_4    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libspatialindex           1.9.3                h9c3ff4c_3    conda-forge
libspatialite             5.0.1                h6ec7341_0    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libthrift                 0.13.0               h5aa387f_6    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libutf8proc               2.6.1                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.41.0               h7f98852_0    conda-forge
libwebp                   1.2.0                h3452ae3_0    conda-forge
libwebp-base              1.2.0                h7f98852_0    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxgboost                1.3.3dev.rapidsai0.18      cuda11.0_0    rapidsai
libxml2                   2.9.10               h72842e0_3    conda-forge
llvmlite                  0.35.0           py38h4630a5e_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
markdown                  3.3.3              pyh9f0ad1d_0    conda-forge
markupsafe                1.1.1            py38h497a2fe_3    conda-forge
mistune                   0.8.4           py38h497a2fe_1003    conda-forge
msgpack-python            1.0.2            py38h1fd1430_1    conda-forge
multidict                 5.1.0            py38h497a2fe_1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
nbclassic                 0.2.6              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py38h578d9bd_3    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
nccl                      2.7.8.1            h4962215_100    nvidia
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
netifaces                 0.10.9          py38h497a2fe_1003    conda-forge
networkx                  2.5                        py_0    conda-forge
nodejs                    14.15.4              h92b4a50_0    conda-forge
notebook                  6.2.0            py38h578d9bd_0    conda-forge
numba                     0.52.0          np1.11py3.8h04863e7_g18825058a_0    numba/label/dev
numpy                     1.19.5           py38h18fd61f_1    conda-forge
nvtx                      0.2.3            py38h497a2fe_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjdk                   11.0.8               hacce0ff_0    conda-forge
openjpeg                  2.4.0                hf7af979_0    conda-forge
openssl                   1.1.1j               h27cfd23_0  
orc                       1.6.5                hd3605a7_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.1.5            py38h51da96c_0    conda-forge
pandoc                    2.11.4               h7f98852_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
panel                     0.10.3             pyhd8ed1ab_0    conda-forge
param                     1.10.1             pyhd3deb0d_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.0            py38ha0e1e83_2    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
poppler                   0.89.0               h2de54a5_5    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 hc2f5b80_3    conda-forge
proj                      7.1.1                h966b41f_3    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.16             pyha770c72_0    conda-forge
protobuf                  3.13.0.1         py38hadf7658_1    conda-forge
psutil                    5.8.0            py38h497a2fe_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py-xgboost                1.3.3dev.rapidsai0.18  cuda11.0py38_0    rapidsai
pyarrow                   1.0.1           py38h3e2403a_14_cuda    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pydeck                    0.5.0              pyh9f0ad1d_0    conda-forge
pyee                      7.0.4              pyh9f0ad1d_0    conda-forge
pygments                  2.8.0              pyhd8ed1ab_0    conda-forge
pyhive                    0.6.3              pyhd3deb0d_0    conda-forge
pynvml                    8.0.4                      py_1    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyppeteer                 0.2.2                      py_1    conda-forge
pyproj                    2.6.1.post1      py38h56787f0_3    conda-forge
pyrsistent                0.17.3           py38h497a2fe_2    conda-forge
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
python                    3.8.8           hffdb5ce_0_cpython    conda-forge
python-confluent-kafka    1.5.0            py38h1e0a361_0    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyviz_comms               2.0.1              pyhd3deb0d_0    conda-forge
pyyaml                    5.4.1            py38h497a2fe_0    conda-forge
pyzmq                     22.0.3           py38h3d7ac18_0    conda-forge
rapids                    0.18.0          cuda11.0_py38_g334c31e_223    rapidsai
rapids-blazing            0.18.0          cuda11.0_py38_g334c31e_223    rapidsai
rapids-xgboost            0.18.0          cuda11.0_py38_g334c31e_223    rapidsai
re2                       2020.10.01           he1b5a44_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
rmm                       0.18.0          cuda_11.0_py38_ga4ee6b7_0    rapidsai
rtree                     0.9.7            py38h02d302b_1    conda-forge
sasl                      0.2.1           py38h950e882_1002    conda-forge
scikit-learn              0.24.1           py38h658cfdd_0    conda-forge
scipy                     1.6.0            py38hb2138dd_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
shapely                   1.7.1            py38ha11d057_1    conda-forge
simpervisor               0.4                pyhd8ed1ab_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sniffio                   1.2.0            py38h578d9bd_1    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
spdlog                    1.7.0                hc9558a2_2    conda-forge
sqlalchemy                1.3.23           py38h497a2fe_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
streamz                   0.6.2              pyh44b312d_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.9.2            py38h578d9bd_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
thrift                    0.13.0           py38h950e882_2    conda-forge
thrift_sasl               0.3.0           py38h1e0a361_1002    conda-forge
tiledb                    2.1.6                h1022b9d_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py38h497a2fe_1    conda-forge
tqdm                      4.58.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
treelite                  1.0.0            py38hd08a91b_0    conda-forge
treelite-runtime          1.0.0                    pypi_0    pypi
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
tzcode                    2021a                h7f98852_0    conda-forge
ucx                       1.9.0+gcd9efd3       cuda11.0_0    rapidsai
ucx-proc                  1.0.0                       gpu    rapidsai
ucx-py                    0.18.0          py38_gcd9efd3_0    rapidsai
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websockets                8.1              py38h497a2fe_3    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py38h578d9bd_4    conda-forge
xarray                    0.17.0             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h9d8b166_2    conda-forge
xgboost                   1.3.3dev.rapidsai0.18  cuda11.0py38_0    rapidsai
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxtst              1.2.3             h516909a_1002    conda-forge
xorg-recordproto          1.14.2            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yarl                      1.6.3            py38h497a2fe_1    conda-forge
zeromq                    4.3.4                h9c3ff4c_0    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                hdf46e1d_0    conda-forge

No errors reported.


__Warning log__
Warning (cuda): CUDA device intialisation problem. Message:Error at driver init: 
[100] Call to cuInit results in CUDA_ERROR_NO_DEVICE:
Exception class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>
Warning (roc): Error initialising ROC: No ROC toolchains found.
Warning (roc): No HSA Agents found, encountered exception when searching: Error at driver init: 
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_quota_us
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_period_us
--------------------------------------------------------------------------------
If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.

=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
=============================================================

`

**Comment by gmarkall** [comment]
Many thanks.  What is the output of `NUMBA_CUDA_LOG_LEVEL=DEBUG python -c "import cudf; cudf.Series([1,2,3])"`?

**Comment by torstendahlen** [comment]
I'm probably very stupid, but I get no output at all when pasting this into the terminal:

NUMBA_CUDA_LOG_LEVEL=DEBUG python -c "import cudf; cudf.Series([1,2,3])"

?

`(rapids-0.18) tordah@LT351:~$ NUMBA_CUDA_LOG_LEVEL=DEBUG python -c "import cudf; cudf.Series([1,2,3])"
(rapids-0.18) tordah@LT351:~$
`

**Comment by torstendahlen** [comment]
Ok, when running the python part in jn I get:

`---------------------------------------------------------------------------
CudaAPIError                              Traceback (most recent call last)
~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in initialize(self)
    236             _logger.info('init')
--> 237             self.cuInit(0)
    238         except CudaAPIError as e:

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in safe_cuda_api_call(*args)
    299             retcode = libfn(*args)
--> 300             self._check_error(fname, retcode)
    301         return safe_cuda_api_call

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in _check_error(self, fname, retcode)
    334                     raise CudaDriverError("CUDA initialized before forking")
--> 335             raise CudaAPIError(retcode, msg)
    336 

CudaAPIError: [100] Call to cuInit results in CUDA_ERROR_NO_DEVICE

During handling of the above exception, another exception occurred:

CudaSupportError                          Traceback (most recent call last)
~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/cudf/core/series.py in __repr__(self)
   1080             )
   1081         else:
-> 1082             output = preprocess.to_pandas().__repr__()
   1083 
   1084         lines = output.split("\n")

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/cudf/core/series.py in to_pandas(self, index, nullable, **kwargs)
   2080         if index is True:
   2081             index = self.index.to_pandas()
-> 2082         s = self._column.to_pandas(index=index, nullable=nullable)
   2083         s.name = self.name
   2084         return s

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/cudf/core/column/column.py in to_pandas(self, index, nullable, **kwargs)
    117             pd_series = pd.Series(pandas_array, copy=False)
    118         elif str(self.dtype) in NUMERIC_TYPES and self.null_count == 0:
--> 119             pd_series = pd.Series(cupy.asnumpy(self.values), copy=False)
    120         else:
    121             pd_series = self.to_arrow().to_pandas(**kwargs)

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/cudf/core/column/column.py in values(self)
    146             raise ValueError("Column must have no nulls.")
    147 
--> 148         return cupy.asarray(self.data_array_view)
    149 
    150     def find_and_replace(

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/cudf/core/column/column.py in data_array_view(self)
     76         View the data as a device array object
     77         """
---> 78         result = cuda.as_cuda_array(self.data)
     79         # Workaround until `.view(...)` can change itemsize
     80         # xref: https://github.com/numba/numba/issues/4829

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/api.py in as_cuda_array(obj)
     58         raise TypeError("*obj* doesn't implement the cuda array interface.")
     59     else:
---> 60         return from_cuda_array_interface(obj.__cuda_array_interface__,
     61                                          owner=obj)
     62 

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py in _require_cuda_context(*args, **kws)
    221     @functools.wraps(fn)
    222     def _require_cuda_context(*args, **kws):
--> 223         with _runtime.ensure_context():
    224             return fn(*args, **kws)
    225 

~/miniconda3/envs/rapids-0.18/lib/python3.8/contextlib.py in __enter__(self)
    111         del self.args, self.kwds, self.func
    112         try:
--> 113             return next(self.gen)
    114         except StopIteration:
    115             raise RuntimeError("generator didn't yield") from None

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py in ensure_context(self)
    119         any top-level Numba CUDA API.
    120         """
--> 121         with driver.get_active_context():
    122             oldctx = self._get_attached_context()
    123             newctx = self.get_or_create_context(None)

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in __enter__(self)
    391         else:
    392             hctx = drvapi.cu_context(0)
--> 393             driver.cuCtxGetCurrent(byref(hctx))
    394             hctx = hctx if hctx.value else None
    395 

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in __getattr__(self, fname)
    278         # Initialize driver
    279         if not self.is_initialized:
--> 280             self.initialize()
    281 
    282         if self.initialization_error is not None:

~/miniconda3/envs/rapids-0.18/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in initialize(self)
    238         except CudaAPIError as e:
    239             self.initialization_error = e
--> 240             raise CudaSupportError("Error at driver init: \n%s:" % e)
    241         else:
    242             self.pid = _getpid()

CudaSupportError: Error at driver init: 
[100] Call to cuInit results in CUDA_ERROR_NO_DEVICE:`

**Comment by gmarkall** [comment]
Thanks for providing the info. I think somehow the cuDF C++ layer is avoiding the error you observe when you only use Numba, and I need to look into why this is.

> I'm probably very stupid, but I get no output at all when pasting this into the terminal:

You're probably not - I suspect there is no output in this case.

**Comment by gmarkall** [comment]
Apologies for the delay in my reply. I'm wondering if the CUDA Runtime API (used by cuDF) is initializing something that doesn't get initialized properly by Numba. Can you try running the following and let me know the output please:

```python
from ctypes import CDLL, POINTER, byref, c_size_t
import sys

cudart = CDLL('libcudart.so')

cudaMemGetInfo = cudart.cudaMemGetInfo
cudaMemGetInfo.argtypes = [POINTER(c_size_t), POINTER(c_size_t)]

free = c_size_t()
total = c_size_t()
err = cudaMemGetInfo(byref(free), byref(total))

if (err):
    print(f"cudaMemGetInfo error is {err}")
    sys.exit(1)

print(f"Free: {free.value} bytes")
print(f"Total: {total.value} bytes")

print("Importing Numba")

from numba import cuda

print("Allocating array")

cuda.device_array(1)

print("Finished")
```

This uses the CUDA Runtime API just prior to using Numba, which I hope will illustrate something about what the problem is, depending on whether it works or prse

**Comment by torstendahlen** [comment]
I will do this as soon as a fix is released for the newest windows preview build affecting the GPU (https://answers.microsoft.com/en-us/insider/forum/all/version-21327-impacts-nvidia-on-wsl-2/413e96d1-0f62-41de-902e-500fab919427?page=2)

**Comment by esc** [comment]
@torstendahlen we never heard back from you on this one. Does this issue persist or should we close it?

**Comment by torstendahlen** [comment]
Please close this issue, it resolved after a new WSL2 update!

**Comment by esc** [comment]
@torstendahlen thank you for following up and closing the issue.

**Comment by gmarkall** [comment]
@torstendahlen If you have chance, could you post here what Windows / WSL2 versions worked please? We have a similar issue in #7104, and I'm not sure what versions were broken / working for you.

**Comment by phdfong** [comment]
I wonder what is the solution here? I have issue with a Ubuntu 20 and Gefore GTX 1650 Ti Mobile.

**Comment by Edamas** [comment]
Same here!

**Comment by gmarkall** [comment]
@Edamas I suggest posting on https://numba.discourse.group with details of your setup (OS, GPU, output of Nvidia-smi, Numba version, installation method, etc)., then someone may be able to suggest troubleshooting steps.

**Comment by Edamas** [comment]
> @Edamas I suggest posting on https://numba.discourse.group with details of your setup (OS, GPU, output of Nvidia-smi, Numba version, installation method, etc)., then someone may be able to suggest troubleshooting steps.

I solved the problem reinstalling the cuda toolkit. Thanks!

**Comment by viktorasb** [comment]
Hi, 
I had the same issue with cuml, cudf etc. versions 23.02 on WSL2, Windows 11 fresh install. 
However rapids versions 22.08 in another anaconda environment worked just fine. 
@gmarkall hints in this forum and discussion https://github.com/numba/numba/issues/7104 saved my day.
Summary: as there is some confusion with installation instructions, especially cuda libraries, review your .bashrc on wsl2.
sudo nano .bashrc

# add these lines at the endo of your .bashrc:
export LD_LIBRARY_PATH="/usr/lib/wsl/lib/"
export NUMBA_CUDA_DRIVER="/usr/lib/wsl/lib/libcuda.so.1"

 BEFORE exports of LD_LIBRARY_PATH and NUMBA_CUDA_DRIVER, because most likely there already is something like this:
 export LD_LIBRARY_PATH=/usr/local/cuda-11.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

save your .bashrc (ctrl^O enter ctrl^X from nano)
At the prompt: 
source .bashrc
start your spyder or anaconda and then set the new environment console.
From GUI you run:
from numba import cuda
cuda.detect()
you should get info about your GPU. If you still get the error, continue looking for mistakes in cuda setup.

if this work around helped, after you type !numba -s you should look for
__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : your version here

Best regards!

**Comment by yosh3289** [comment]
> Hi, I had the same issue with cuml, cudf etc. versions 23.02 on WSL2, Windows 11 fresh install. However rapids versions 22.08 in another anaconda environment worked just fine. @gmarkall hints in this forum and discussion #7104 saved my day. Summary: as there is some confusion with installation instructions, especially cuda libraries, review your .bashrc on wsl2. sudo nano .bashrc
> 
> ### add these lines at the end of your .bashrc:
> export LD_LIBRARY_PATH="/usr/lib/wsl/lib/" export NUMBA_CUDA_DRIVER="/usr/lib/wsl/lib/libcuda.so.1"
> 
> BEFORE exports of LD_LIBRARY_PATH and NUMBA_CUDA_DRIVER, because most likely there already is something like this: export LD_LIBRARY_PATH=/usr/local/cuda-11.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
> 
> save your .bashrc (ctrl^O enter ctrl^X from nano) At the prompt: source .bashrc start your spyder or anaconda and then set the new environment console. From GUI you run: from numba import cuda cuda.detect() you should get info about your GPU. If you still get the error, continue looking for mistakes in cuda setup.
> 
> if this work around helped, after you type !numba -s you should look for **CUDA Information** CUDA Device Initialized : True CUDA Driver Version : your version here
> 
> Best regards!

Adding extra lines in .bashrc resolved my issue!! THX!!

**Comment by gmarkall** [comment]
@Vonct Please start a new post on the Discourse group to ask for help with this: https://numba.discourse.group

**Comment by Rj1318** [comment]
I resolved this issue using four steps in September 2023. Before addressing the problem, I took the following two preparatory actions:

1. Installed CUDA from NVIDIA.
2. Updated Ubuntu to the latest available version. I encountered this error in Ubuntu 22.04.3 LTS, so I had to upgrade it to the regular 22.04 version.

Here's the solution I followed:

a. Navigate to the following link: https://docs.rapids.ai/install

Info: Code after $ 

1. Created a Conda environment named "rapids-23.08" before installing the code. I used the latest Rapids version found on that link for the environment creation:

```bash/open terminal 
$conda create --name rapids-23.08
```

3. Activated the "rapids-23.08" environment (or whichever version is currently the latest):

$conda activate rapids-23.08
```

4. Opened the `.condarc` configuration file using the `nano` text editor:

$nano ~/.condarc
```

5. Added the following lines to the `.condarc` file, specifying flexible channel priorities:

channels:
  - defaults
  - conda-forge
  - <other-channels>  # Replace with any additional channels listed
channel_priority: flexible


Make sure to include the line `channel_priority: flexible` and save the file.

6. Ensured that I was still in the activated Conda environment.

5. Went to the provided link and followed the installation instructions:

$conda create --solver=libmamba -n rapids-23.08 -c rapidsai -c conda-forge -c nvidia \
    rapids=23.08 python=3.10 cuda-version=11.2
```

By following these steps, I successfully resolved the issue while setting flexible Conda channel priorities in the "rapids-23.08" environment.

**Comment by gmarkall** [comment]
@rj1318 Thanks for sharing your information.

In general (for anyone looking at this issue) for any future discussion related to issues like this one, new threads should be opened on Discourse (https://numba.discourse.group) or a new issue, if the problem is likely to be a problem with Numba and not a configuration issue on the system in question.
