### ISSUE TITLE
Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR

### ISSUE THREAD

**Issue by miguelcarcamov** [numba/numba#7006]
Hi there,

I am using numba without conda in Manjaro OS. That is, just using the nvidia driver and nvidia toolkit system installations. Numba was working ok until Manjaro updated the driver and the CUDA Toolkit in my system. Now I am getting the following error: "numba.cuda.cudadrv.driver.LinkerError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal   : Unsupported .version 7.3; current version is '7.2'"

- I have uninstalled numba with pip and then install it again and the error keeps coming.
- I have run numba -s and I get no errors:

```
System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2021-05-07 12:26:36.702571
UTC start time                                : 2021-05-07 16:26:36.702576
Running time (s)                              : 2.191629

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : ivybridge
CPU Count                                     : 8
Number of accessible CPUs                     : 8
List of accessible CPUs cores                 : 0 1 2 3 4 5 6 7
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 64bit aes avx cmov cx16 cx8 f16c
                                                fsgsbase fxsr mmx pclmul popcnt
                                                rdrnd sahf sse sse2 sse3 sse4.1
                                                sse4.2 ssse3 xsave xsaveopt

Memory Total (MB)                             : 15958
Memory Available (MB)                         : 12346

__OS Information__
Platform Name                                 : Linux-5.9.16-1-MANJARO-x86_64-with-glibc2.33
Platform Release                              : 5.9.16-1-MANJARO
OS Name                                       : Linux
OS Version                                    : #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020
OS Specific Version                           : ?
Libc Version                                  : glibc 2.33

__Python Information__
Python Compiler                               : GCC 10.2.0
Python Implementation                         : CPython
Python Version                                : 3.9.4
Python Locale                                 : en_GB.UTF-8

__LLVM Information__
LLVM Version                                  : 10.0.1

__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : 11020
CUDA Detect Output:
Found 1 CUDA devices
id 0    b'GeForce GTX 1070 Ti'                              [SUPPORTED]
                      compute capability: 6.1
                           pci device id: 0
                              pci bus id: 1
Summary:
	1/1 devices are supported

CUDA Libraries Test Output:
Finding cublas from CUDA_HOME
	named  libcublas.so.11.4.2.10064
	trying to open library...	ok
Finding cusparse from CUDA_HOME
	named  libcusparse.so.11.5.0.58
	trying to open library...	ok
Finding cufft from CUDA_HOME
	named  libcufft.so.10.4.2.58
	trying to open library...	ok
Finding curand from CUDA_HOME
	named  libcurand.so.10.2.4.58
	trying to open library...	ok
Finding nvvm from CUDA_HOME
	named  libnvvm.so.4.0.0
	trying to open library...	ok
Finding cudart from CUDA_HOME
	named  libcudart.so.11.3.58
	trying to open library...	ok
Finding cudadevrt from CUDA_HOME
	named  libcudadevrt.a
Finding libdevice from CUDA_HOME
	searching for compute_20...	ok
	searching for compute_30...	ok
	searching for compute_35...	ok
	searching for compute_50...	ok


__ROC information__
ROC Available                                 : False
ROC Toolchains                                : None
HSA Agents Count                              : 0
HSA Agents:
None
HSA Discrete GPUs Count                       : 0
HSA Discrete GPUs                             : None

__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : True
+-->TBB imported successfully.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
NUMBA_CUDA_DRIVER                             : /usr/lib/libcuda.so

__Conda Information__
Conda not available.

__Installed Packages__
Package             Version
------------------- -----------------
appdirs             1.4.4
apsw                3.35.4.post1
arandr              0.1.10
argcomplete         1.10.0
argon2-cffi         20.1.0
asn1crypto          1.4.0
astropy             4.2
astropy-healpix     0.5
astropy-helpers     4.0.1
astroquery          0.4.1
async-generator     1.10
attrs               20.3.0
autopep8            1.5.7
backcall            0.2.0
beautifulsoup4      4.8.0
bleach              3.3.0
blurhash            1.1.4
btrfsutil           5.11.1
CacheControl        0.12.6
cchardet            2.1.7
cffi                1.14.5
chardet             3.0.4
cloudpickle         1.6.0
colorama            0.4.4
configobj           5.1.0.dev0
contextlib2         0.6.0.post1
cryptography        3.4.7
css-parser          1.0.6
cssselect           1.1.0
cupy                8.6.0
cycler              0.10.0
dask                2021.4.1
dask-ms             0.2.6
decorator           5.0.7
defusedxml          0.7.1
distlib             0.3.1
distro              1.5.0
dnspython           1.16.0
docopt              0.6.2
docutils            0.16
docx2txt            0.8
EbookLib            0.17.1
entrypoints         0.3
extract-msg         0.23.1
fastrlock           0.6
feedparser          5.2.1
fsspec              2021.4.0
funcsigs            1.0.2
future              0.18.2
healpy              1.14.0
html2text           2020.1.16
html5-parser        0.4.9
html5lib            1.1
idna                3.1
ifaddr              0.1.7
imageio             2.9.0
IMAPClient          2.1.0
importlib-metadata  3.10.0
ipykernel           5.5.3
ipython             7.22.0
ipython-genutils    0.2.0
ipywidgets          7.6.3
isodate             0.6.0
JACK-Client         0.5.3
jedi                0.18.0
jeepney             0.6.0
Jinja2              2.11.3
joblib              1.0.1
jsonschema          3.2.0
jupyter-client      6.1.12
jupyter-console     6.4.0
jupyter-core        4.7.1
jupyterlab-pygments 0.1.2
keyring             23.0.1
kiwisolver          1.3.1
lic                 0.4.5
llvmlite            0.36.0
locket              0.2.1
louis               3.17.0
lxml                4.6.3
Mako                1.1.4
Markdown            3.3.4
MarkupSafe          1.1.1
Mastodon.py         1.5.1
matplotlib          3.3.4
mechanize           0.4.5
meld                3.20.3
mistune             0.8.4
msgpack             1.0.2
nbclient            0.5.3
nbconvert           6.0.7
nbformat            5.1.3
nest-asyncio        1.5.1
netifaces           0.10.9
netsnmp-python      1.0a1
notebook            6.3.0
npyscreen           4.10.5
numba               0.53.1
numpy               1.20.1
olefile             0.46
ordered-set         4.0.2
packaging           20.9
pacman-mirrors      4.21.2
palettable          3.3.0
pandas              1.2.4
pandocfilters       1.4.3
parso               0.8.1
partd               1.2.0
pdfminer.six        20181108
pep517              0.10.0
pexpect             4.8.0
pickleshare         0.7.5
Pillow              8.2.0
pip                 21.1.1
pkginfo             1.7.0
ply                 3.11
progress            1.5
prometheus-client   0.10.1
prompt-toolkit      3.0.18
protonvpn-cli       2.2.6
prox-tv             3.2.1
proxmin             0.6.11
psutil              5.8.0
ptyprocess          0.7.0
py7zr               0.11.3
pycairo             1.20.0
pychm               0.8.6
pycodestyle         2.7.0
pycountry           20.7.3
pycparser           2.20
pycryptodome        3.10.1
pyerfa              1.7.2
Pygments            2.8.1
PyGObject           3.40.1
pynufft             2021.0.2
pyopencl            2021.1.6
PyOpenGL            3.1.5
pyOpenSSL           20.0.1
pyparsing           2.4.7
PyQt5               5.15.4
PyQt5-sip           12.8.1
PyQtWebEngine       5.15.4
pyrsistent          0.17.3
PySide2             5.15.2
pysmbc              1.0.23
PySocks             1.7.1
python-casacore     3.4.0
python-dateutil     2.8.1
python-libtorrent   1.2.11
python-magic        0.4.18
python-pptx         0.6.18
python-xlib         0.29
pythondialog        3.5.1
pytools             2021.2.3
pytz                2021.1
pywal               3.3.0
PyYAML              5.4.1
pyzmq               22.0.3
ranger-fm           1.9.3
readme-renderer     29.0
regex               2021.4.4
regions             0.4
reikna              0.7.5
reportlab           3.5.66
reproject           0.7.1
requests            2.25.1
requests-toolbelt   0.9.1
resolvelib          0.5.4
retrying            1.3.3
rfc3986             1.4.0
scipy               1.6.1
seaborn             0.11.1
SecretStorage       3.3.1
Send2Trash          1.5.0
setuptools          54.2.0
shiboken2           5.15.2
six                 1.12.0
sortedcontainers    2.3.0
soupsieve           2.2.1
SpeechRecognition   3.8.1
speedtest-cli       2.1.3
SQLAlchemy          1.3.22
streamlink          2.0.0+22.gb9d0d18
team                1.0
terminado           0.9.4
terminator          2.1.1
testpath            0.4.4
textract            1.6.3
texttable           1.6.3
toml                0.10.2
toolz               0.11.1
tornado             6.1
tqdm                4.59.0
traitlets           5.0.5
twine               3.4.1
tzlocal             1.5.1
ueberzug            18.1.9
ufw                 0.36
unrardll            0.1.4
urllib3             1.26.4
validate            5.1.0.dev0
visvis              1.13.0
wcwidth             0.2.5
webencodings        0.5.1
websocket-client    0.58.0
wheel               0.36.2
widgetsnbextension  3.5.1
xarray              0.17.0
xlrd                1.2.0
XlsxWriter          1.3.9
zeroconf            0.28.8
zipp                3.4.1

No errors reported.


__Warning log__
Warning (roc): Error initialising ROC: No ROC toolchains found.
Warning (roc): No HSA Agents found, encountered exception when searching: Error at driver init: 
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:
Warning: Conda not available.
 Error was [Errno 2] No such file or directory: 'conda'

--------------------------------------------------------------------------------
```
I will leave here the result of my nvcc and nvidia-smi commands:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
```

```
Fri May  7 12:29:13 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 107...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   57C    P0    36W / 180W |    200MiB /  8116MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       650      G   /usr/lib/Xorg                     144MiB |
|    0   N/A  N/A      1272      G   protonmail-bridge                   5MiB |
|    0   N/A  N/A      1425      G   ...java-11-openjdk//bin/java        7MiB |
|    0   N/A  N/A      2150      G   ...AAAAAAAAA= --shared-files       40MiB |
+-----------------------------------------------------------------------------+
```
Does anyone know how to fix this?

Cheers

**Comment by gmarkall** [comment]
It looks like you have the CUDA Toolkit version 11.3 but only a driver version of 11.2. You will need to upgrade to a later driver of at least version 465.19.01, to match CUDA toolkit 11.3 (See Table 2 of https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).

Note that although Forward Compatibility is a feature of the CUDA Toolkit 11.x series, which allows you to use code compiled with a newer toolkit than the current driver version, Numba presently doesn't implement support for Forward Compatibility.

**Comment by gmarkall** [comment]
> @gmarkall I recently encountered a similar problem when trying to make use of Forward Compatibility (driver 11.2, toolkit 11.3). It's not trivial to me what's the "support" you are referring to. Doesn't it work out of box?

It works out of the box for CUDA C/C++ as far as I am aware - however, because Numba doesn't know anything about forward compatibility it always tries to generate PTX for the latest version supported by the toolkit and not the driver, so the driver refuses to accept it for linking with the error message reported in this issue:

> `numba.cuda.cudadrv.driver.LinkerError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal : Unsupported .version 7.3; current version is '7.2'`

**Comment by gmarkall** [comment]
Closing this issue as no further activity has taken place in a couple of weeks, and the issue appears to be unrelated to Numba.

**Comment by Algomorph** [comment]
@gmarkall Sorry if this actually warrants a new issue here, but I'm getting the same issue right now on numba 0.55.0 release, only now it's `ptxas application ptx input, line 9; fatal   : Unsupported .version 7.6; current version is '7.5'`. My NVidia driver and version seem to correspond exactly, i.e. CUDA 11.5.1 & Driver Version: 495.29.05 (CUDA [release notes, driver / toolkit compat table](https://docs.nvidia.com/cuda/archive/11.5.1/cuda-toolkit-release-notes/index.html#cuda-major-component-versions))

You write:

> It works out of the box for CUDA C/C++ as far as I am aware - however, because Numba doesn't know anything about forward compatibility it always tries to generate PTX for the latest version supported by the toolkit and not the driver, so the driver refuses to accept it for linking with the error message reported in this issue

And then you closed this issue for lack of activity and
> issue appears to be unrelated to Numba

If the CUDA compiler is trying to generate ptx for an architecture unsupported by my driver (which, by the way, it doesn't if I do any direct CUDA compilations via `nvcc`), then what exactly is the culprit here? I mean, what component within `numba` would be in charge of picking the right `ptx` architecture, so that I can understand where to report this issue / how to fix it?

**Comment by gmarkall** [comment]
What's the output of `numba -s`?

**Comment by Algomorph** [comment]
That would be:
```
System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2022-01-20 16:21:25.982710
UTC start time                                : 2022-01-20 21:21:25.982713
Running time (s)                              : 0.638469

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : znver2
CPU Count                                     : 32
Number of accessible CPUs                     : 32
List of accessible CPUs cores                 : 0-31
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 64bit adx aes avx avx2 bmi bmi2
                                                clflushopt clwb clzero cmov cx16
                                                cx8 f16c fma fsgsbase fxsr lzcnt
                                                mmx movbe mwaitx pclmul popcnt
                                                prfchw rdpid rdrnd rdseed sahf sha
                                                sse sse2 sse3 sse4.1 sse4.2 sse4a
                                                ssse3 wbnoinvd xsave xsavec
                                                xsaveopt xsaves

Memory Total (MB)                             : 64283
Memory Available (MB)                         : 47443

__OS Information__
Platform Name                                 : Linux-5.4.0-96-generic-x86_64-with-glibc2.29
Platform Release                              : 5.4.0-96-generic
OS Name                                       : Linux
OS Version                                    : #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022
OS Specific Version                           : ?
Libc Version                                  : glibc 2.31

__Python Information__
Python Compiler                               : GCC 9.3.0
Python Implementation                         : CPython
Python Version                                : 3.8.10
Python Locale                                 : en_US.UTF-8

__Numba Toolchain Versions__
Numba Version                                 : 0.55.0
llvmlite Version                              : 0.38.0

__LLVM Information__
LLVM Version                                  : 11.1.0

__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : (11, 5)
CUDA Runtime Version                          : 11060
CUDA NVIDIA Bindings Available                : False
CUDA NVIDIA Bindings In Use                   : False
CUDA Detect Output:
Found 1 CUDA devices
id 0    b'NVIDIA GeForce GTX 1070'                              [SUPPORTED]
                      Compute Capability: 6.1
                           PCI Device ID: 0
                              PCI Bus ID: 4
                                    UUID: GPU-8efb77f4-7515-7493-3252-541a92e773e6
                                Watchdog: Enabled
             FP32/FP64 Performance Ratio: 32
Summary:
	1/1 devices are supported

CUDA Libraries Test Output:
Finding nvvm from System
	named  libnvvm.so.4.0.0
	trying to open library...	ok
Finding cudart from System
	named  libcudart.so.11.6.55
	trying to open library...	ok
Finding cudadevrt from System
	named  libcudadevrt.a
Finding libdevice from System
	searching for compute_20...	ok
	searching for compute_30...	ok
	searching for compute_35...	ok
	searching for compute_50...	ok


__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : False
+--> Disabled due to Unknown import problem.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda not available.

__Installed Packages__
Package                        Version              Editable project location
------------------------------ -------------------- ---------------------------------
absl-py                        0.11.0
addict                         2.4.0
antlr4-python3-runtime         4.8
anyio                          3.3.4
appdirs                        1.4.4
apsw                           3.28.0.post1
apturl                         0.5.2
argon2-cffi                    21.1.0
asgiref                        3.3.1
asn1crypto                     0.24.0
asttokens                      2.0.4
astunparse                     1.6.3
async-generator                1.10
attrs                          21.2.0
Automat                        20.2.0
Babel                          2.9.1
backcall                       0.2.0
bcrypt                         3.1.7
beautifulsoup4                 4.8.2
black                          21.4b2
bleach                         4.1.0
blinker                        1.4
Brlapi                         0.7.0
bs4                            0.0.1
build                          0.6.0.post1
cachetools                     4.2.1
certifi                        2021.10.8
cffi                           1.15.0
chardet                        3.0.4
charset-normalizer             2.0.7
cheap-repr                     0.4.5
chrome-gnome-shell             0.0.0
click                          8.0.1
cloudpickle                    1.6.0
cmake-example                  0.0.1
colorama                       0.4.3
command-not-found              0.3
commonmark                     0.9.1
constantly                     15.1.0
coverage                       5.5
cryptography                   2.8
css-parser                     1.0.4
cssselect                      1.1.0
cssutils                       1.0.2
cupshelpers                    1.0
cupy-cuda114                   9.4.0
cycler                         0.11.0
Cython                         0.29.23
dbus-python                    1.2.16
debugpy                        1.5.1
decorator                      4.4.2
defer                          1.0.6
defusedxml                     0.7.1
Deprecated                     1.2.13
deprecation                    2.1.0
detectron2                     0.4                  /home/algomorph/Garage/detectron2
dill                           0.3.4
distro                         1.4.0
distro-info                    0.23ubuntu1
Django                         3.1.5
dnspython                      1.16.0
docopt                         0.6.2
docutils                       0.17.1
dq3d                           0.3.6
duplicity                      0.8.12.0
easydict                       1.9
entrypoints                    0.3
et-xmlfile                     1.0.1
executing                      0.5.4
ext-argparse                   0.1.2
fasteners                      0.14.1
fastrlock                      0.5
feedparser                     5.2.1
ffmpeg                         1.4
flake8                         3.9.2
flatbuffers                    1.12
future                         0.18.2
fvcore                         0.1.5.post20210402
gast                           0.3.3
glfw                           2.1.0
google-auth                    1.24.0
google-auth-oauthlib           0.4.2
google-pasta                   0.2.0
gpg                            1.13.1-unknown
grpcio                         1.32.0
h5py                           2.10.0
hickle                         4.0.4
html2text                      2020.1.16
html5-parser                   0.4.9
html5lib                       1.0.1
httplib2                       0.14.0
hydra-core                     1.1.1
hyperlink                      20.0.1
hyperopt                       0.2.5
icecream                       2.1.1
idna                           3.3
ifaddr                         0.1.6
imageio                        2.9.0
imageio-ffmpeg                 0.4.3
importlib-metadata             4.8.1
importlib-resources            5.4.0
incremental                    17.5.0
iniconfig                      1.1.1
install                        1.3.4
intel-openmp                   2021.1.2
iopath                         0.1.8
iotop                          0.6
ipykernel                      6.5.0
ipython                        7.29.0
ipython-genutils               0.2.0
ipywidgets                     7.6.5
itemadapter                    0.2.0
itemloaders                    1.0.4
jdcal                          1.4.1
jedi                           0.18.0
Jinja2                         3.0.3
jmespath                       0.10.0
joblib                         1.1.0
json5                          0.9.6
jsonschema                     4.2.1
jupyter                        1.0.0
jupyter-client                 7.0.6
jupyter-console                6.2.0
jupyter-core                   4.9.1
jupyter-packaging              0.11.0
jupyter-qtconsole-colorschemes 0.8.1
jupyter-server                 1.11.2
jupyterlab                     3.2.2
jupyterlab-pygments            0.1.2
jupyterlab-server              2.8.2
jupyterlab-widgets             1.0.2
Keras-Preprocessing            1.1.2
keyring                        18.0.1
keyrings.alt                   3.4.0
kiwisolver                     1.3.2
kornia                         0.4.1
language-selector              0.1
launchpadlib                   1.10.13
lazr.restfulclient             0.14.2
lazr.uri                       1.0.3
llvmlite                       0.38.0
lockfile                       0.12.2
louis                          3.12.0
lxml                           4.5.0
macaroonbakery                 1.3.1
Mako                           1.1.0
mariadb                        1.0.8
Markdown                       3.1.1
MarkupSafe                     2.0.1
matplotlib                     3.4.3
matplotlib-inline              0.1.3
mccabe                         0.6.1
mechanize                      0.4.5
mistune                        0.8.4
mkl                            2021.1.1
mkl-include                    2021.1.1
module-a                       0.0.1
module-b                       0.0.1
monotonic                      1.5
moviepy                        1.0.3
msgpack                        0.6.2
multipledispatch               0.6.0
mutagen                        1.44.0
mypy                           0.910
mypy-extensions                0.4.3
nbclassic                      0.3.4
nbclient                       0.5.5
nbconvert                      6.2.0
nbformat                       5.1.3
nest-asyncio                   1.5.1
netifaces                      0.10.4
networkx                       2.5
NeuralNRT                      1.0
ninja                          1.10.0.post2
nnrt                           0.1.1
nose                           1.3.7
notebook                       6.4.5
numba                          0.55.0
numpy                          1.20.3
oauth                          1.0.1
oauthlib                       3.1.0
olefile                        0.46
omegaconf                      2.1.0rc1
open3d                         0.14.1+4dea5bebb
opencv-python                  4.4.0.46
openpyxl                       3.0.5
opt-einsum                     3.3.0
packaging                      21.2
pandas                         1.3.4
pandocfilters                  1.5.0
paramiko                       2.6.0
parsel                         1.6.0
parso                          0.8.2
pathspec                       0.8.1
pbr                            5.5.1
pep517                         0.11.0
pexpect                        4.8.0
pickleshare                    0.7.5
Pillow                         8.4.0
pip                            21.3.1
pip-autoremove                 0.9.1
pip-search                     0.0.7
Pivy                           0.6.5
pkginfo                        1.7.1
plotly                         4.14.3
pluggy                         0.13.1
plumbum                        1.6.8
plyfile                        0.7.2
portalocker                    2.3.0
proglog                        0.1.9
progressbar2                   3.53.1
prometheus-client              0.12.0
prompt-toolkit                 3.0.22
Protego                        0.1.16
protobuf                       3.14.0
ptyprocess                     0.7.0
py                             1.10.0
pyasn1                         0.4.8
pyasn1-modules                 0.2.8
pybind11                       2.6.2
pybind11-stubgen               0.8.7
pycairo                        1.16.2
pychm                          0.8.6
pycocotools                    2.0.2
pycodestyle                    2.7.0
pycparser                      2.21
pycrypto                       2.6.1
pycuda                         2020.1
pycups                         1.9.73
PyDispatcher                   2.0.5
pydot                          1.4.2
pyflakes                       2.3.1
pyglet                         1.5.18
PyGLM                          1.99.3
Pygments                       2.10.0
PyGObject                      3.36.0
PyHamcrest                     2.0.2
PyJWT                          1.7.1
pymacaroons                    0.13.0
PyNaCl                         1.3.0
pynvml                         8.0.4
PyOpenGL                       3.1.5
pyOpenSSL                      19.0.0
pyparsing                      2.4.7
PyPDF2                         1.26.0
PyQt5                          5.14.1
PyQtWebEngine                  5.14.0
pyquaternion                   0.9.9
pyRFC3339                      1.1
pyrsistent                     0.18.0
PySnooper                      0.4.3
pytest                         6.2.5
pytest-cov                     2.12.1
pytest-cover                   3.0.0
pytest-coverage                0.0
python-apt                     2.0.0+ubuntu0.20.4.6
python-dateutil                2.8.2
python-debian                  0.1.36ubuntu1
python-utils                   2.5.6
pytools                        2021.2.3
pytorch3d                      0.6.0
pytube                         11.0.1
pytz                           2021.3
PyWavelets                     1.1.1
pyxattr                        0.6.1
pyxdg                          0.26
PyYAML                         6.0
pyzmq                          22.3.0
qtconsole                      4.7.7
QtPy                           1.9.0
queuelib                       1.5.0
readme-renderer                29.0
regex                          2021.4.4
reportlab                      3.5.34
repoze.lru                     0.7
requests                       2.26.0
requests-oauthlib              1.3.0
requests-toolbelt              0.9.1
requests-unixsocket            0.2.0
retrying                       1.3.3
rfc3986                        1.5.0
rich                           10.12.0
Routes                         2.4.1
rsa                            4.7
ruamel.yaml                    0.17.16
ruamel.yaml.clib               0.2.6
scikit-image                   0.18.1
scikit-learn                   1.0.1
scikit-tensor-py3              0.4.1
scipy                          1.7.2
Scrapy                         2.4.1
screen-resolution-extra        0.0.0
SecretStorage                  2.3.1
Send2Trash                     1.8.0
service-identity               18.1.0
setuptools                     58.5.3
simplejson                     3.16.0
sip                            4.19.21
six                            1.16.0
sklearn                        0.0
sniffio                        1.2.0
snoop                          0.3.0
soupsieve                      1.9.5
sqlparse                       0.4.1
system-service                 0.3
systemd-python                 234
tabulate                       0.8.9
tbb                            2021.1.1
tensorboard                    2.4.1
tensorboard-plugin-wit         1.8.0
tensorboardX                   2.1
tensorflow-estimator           2.4.0
tensorly                       0.5.0
termcolor                      1.1.0
terminado                      0.12.1
testpath                       0.5.0
testresources                  2.0.1
threadpoolctl                  3.0.0
tifffile                       2021.1.14
toml                           0.10.2
tomli                          1.2.1
tomlkit                        0.7.2
torch                          1.10.0+cu113
torchaudio                     0.10.0+cu113
TorchSnooper                   0.8
torchvision                    0.11.1+cu113
tornado                        6.1
tqdm                           4.62.3
traitlets                      5.1.1
transformations                2020.1.1
trimesh                        3.9.1
twine                          3.4.2
Twisted                        20.3.0
typing-extensions              3.7.4.3
ubuntu-advantage-tools         27.5
ubuntu-drivers-common          0.0.0
ufw                            0.36
unattended-upgrades            0.1
urllib3                        1.26.7
usb-creator                    0.3.7
vtk                            9.0.1
w3lib                          1.22.0
wadllib                        1.3.3
wcwidth                        0.2.5
webencodings                   0.5.1
WebOb                          1.8.5
websocket-client               1.2.1
Werkzeug                       1.0.1
wheel                          0.37.0
widgetsnbextension             3.5.2
wrapt                          1.12.1
xkit                           0.0.0
yacs                           0.1.8
youtube-dl                     2020.3.24
zeroconf                       0.24.4
zipp                           3.6.0
zope.interface                 4.7.1

No errors reported.


__Warning log__
Warning: Conda not available.
 Error was [Errno 2] No such file or directory: 'conda'

Warning (psutil): psutil cannot be imported. For more accuracy, consider installing it.
--------------------------------------------------------------------------------
If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.

=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
=============================================================

```

**Comment by gmarkall** [comment]
Thanks for the info. You're using the CUDA 11.6 toolkit with a driver that only supports up to CUDA 11.5:

```
CUDA Driver Version                           : (11, 5)
CUDA Runtime Version                          : 11060
```

You need to either:

- Update to a driver that supports CUDA 11.6 (510.39.01 or above), or
- Downgrade to using the CUDA toolkit 11.5.

To use CUDA 11.5, I think you will be able to do something like:

```
conda install conda-forge::cudatoolkit=11.5
```

**Comment by Algomorph** [comment]
@gmarkall thank you so much for your help, I really appreciate it! I saw that one too and was quite baffled/suspicious at the time...

Jolly, CUDA 11.6 runtime (`CUDA Runtime Version 11060`) somehow mysteriously crept onto my Ubuntu system (although, if my memory isn't failing me, I explicitly chose not to upgrade this). Running `sudo apt autoremove` actually removed the impostor runtime and solved this issue for me, and now `numba -s | grep "Runtime"` produces `CUDA Runtime Version                          : 11050`.

Not using `conda` here, just plain old `pip`, and my tests using `numba` are now passing! Thank you!

**Comment by iegorval** [comment]
I have a similar issue and I am not sure to which version I should change my toolkit so that it does not break the CUDA installation but works with `numba`. Any help is appreciated.

```
__Time Stamp__
Report started (local time)                   : 2022-05-18 12:14:22.268590
UTC start time                                : 2022-05-18 10:14:22.268596
Running time (s)                              : 0.844907

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : broadwell
CPU Count                                     : 48
Number of accessible CPUs                     : 32
List of accessible CPUs cores                 : 0-44
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 64bit adx aes avx avx2 bmi bmi2
                                                cmov cx16 cx8 f16c fma fsgsbase
                                                fxsr invpcid lzcnt mmx movbe
                                                pclmul popcnt prfchw rdrnd rdseed
                                                rtm sahf sse sse2 sse3 sse4.1
                                                sse4.2 ssse3 xsave xsaveopt

Memory Total (MB)                             : 257836
Memory Available (MB)                         : 158245

__OS Information__
Platform Name                                 : Linux-5.4.0-90-generic-x86_64-with-debian-buster-sid
Platform Release                              : 5.4.0-90-generic
OS Name                                       : Linux
OS Version                                    : #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021
OS Specific Version                           : ?
Libc Version                                  : glibc 2.26

__Python Information__
Python Compiler                               : GCC 7.5.0
Python Implementation                         : CPython
Python Version                                : 3.7.12
Python Locale                                 : en_US.UTF-8

__Numba Toolchain Versions__
Numba Version                                 : 0.55.1
llvmlite Version                              : 0.38.0

__LLVM Information__
LLVM Version                                  : 11.1.0

__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : (11, 0)
CUDA Runtime Version                          : 11030
CUDA NVIDIA Bindings Available                : False
CUDA NVIDIA Bindings In Use                   : False
CUDA Detect Output:
Found 2 CUDA devices
id 0    b'Tesla V100-PCIE-16GB'                              [SUPPORTED]
                      Compute Capability: 7.0
                           PCI Device ID: 0
                              PCI Bus ID: 129
                                    UUID: GPU-201c187f-26e7-4b76-4ff0-5ddab737bba7
                                Watchdog: Disabled
             FP32/FP64 Performance Ratio: 2
id 1    b'Tesla V100-PCIE-16GB'                              [SUPPORTED]
                      Compute Capability: 7.0
                           PCI Device ID: 0
                              PCI Bus ID: 133
                                    UUID: GPU-a2c7960a-6d75-9df8-3908-b1ef39801fb2
                                Watchdog: Disabled
             FP32/FP64 Performance Ratio: 2
Summary:
        2/2 devices are supported

CUDA Libraries Test Output:
Finding nvvm from System
        named  libnvvm.so.4.0.0
        trying to open library...       ok
Finding cudart from System
        named  libcudart.so.11.3.58
        trying to open library...       ok
Finding cudadevrt from System
        named  libcudadevrt.a
Finding libdevice from System
        searching for compute_20...     ok
        searching for compute_30...     ok
        searching for compute_35...     ok
        searching for compute_50...     ok


__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : False
+--> Disabled due to Unknown import problem.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda not available.
```

From `nvcc --version`:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
From `nvidia-smi`:
```
| NVIDIA-SMI 450.156.00   Driver Version: 450.156.00   CUDA Version: 11.0     |
```

**Comment by gmarkall** [comment]
> I have a similar issue and I am not sure to which version I should change my toolkit so that it does not break the CUDA installation but works with `numba`. Any help is appreciated.

You have the CUDA driver 11.0, but Numba is picking up a CUDA 11.3 toolkit, which generates PTX too new for the driver:

> CUDA Driver Version                           : (11, 0)
> CUDA Runtime Version                          : 11030

You also have a CUDA toolkit 10.1 installed somewhere, which is on the path and where `nvcc` is getting found from:

> From `nvcc --version`:
> 
> ```
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Sun_Jul_28_19:07:16_PDT_2019
> Cuda compilation tools, release 10.1, V10.1.243
> ```

I think the best route forward would be to install the CUDA 11.0 toolkit from https://developer.nvidia.com/cuda-11-0-3-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu then set the `CUDA_HOME` environment variable to its location, e.g.:

```
export CUDA_HOME=/usr/local/cuda-11.0
```

prior to running Numba.

If you continue to have issues, please open a post on the Discourse group (https://numba.discourse.group), which is more suited to support queries - we try to keep the issue tracker on Github for tracking feature requests and bug reports.

**Comment by pk1996** [comment]
I have a similar problem. The exact error is 0 
```
numba.cuda.cudadrv.driver.LinkerError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal   : Unsupported .version 7.3; current version is '7.2'
```

From the above comments I can see that there is a mismatch between the cuda driver and cuda toolkit.
FYI, cuda driver shows 11.2 via nvidia-smi and I have cuda toolkit 11.3.

I am skeptical of upgrading my cuda driver as I am on a common system across multiple users. On the other hand I don't see a 11.2 cuda toolkit. 

Any insights into this issue? How can I resolve this without rouching the nvidia driver! 

Thanks!

**Comment by haiduo** [comment]
> Thanks for the info. You're using the CUDA 11.6 toolkit with a driver that only supports up to CUDA 11.5:
> 
> ```
> CUDA Driver Version                           : (11, 5)
> CUDA Runtime Version                          : 11060
> ```
> 
> You need to either:
> 
> * Update to a driver that supports CUDA 11.6 (510.39.01 or above), or
> * Downgrade to using the CUDA toolkit 11.5.
> 
> To use CUDA 11.5, I think you will be able to do something like:
> 
> ```
> conda install conda-forge::cudatoolkit=11.5
> ```

Yes!  That " conda install conda-forge::cudatoolkit=11.2 " is also ok to cuda=11.2

**Comment by asaoulis** [comment]
I'm getting the following diagnostic error when running `python -m numba -s`:

```
Finding cudadevrt from CUDA_HOME
        named  cudadevrt.lib
        ERROR: failed to find cudadevrt:
cudadevrt.lib not found
```

Earlier today, I found this thread and installed the 11.3 toolkit to replace 11.2, and removed any references to 11.2 in my environment, but the problem above persists. In the same `numba -s` command:

```
__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : 11.3
CUDA Runtime Version                          : 11.3
CUDA NVIDIA Bindings Available                : True
CUDA NVIDIA Bindings In Use                   : False
```

nvcc -V :

```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:24:09_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
```

nvidia-smi:

```
| NVIDIA-SMI 466.47       Driver Version: 466.47       CUDA Version: 11.3     |
```

So as far as I can tell, everything should be using the same version `11.3` - any ideas what isn't working? When I try to use `numba.cuda` in a Python script I get the following (clearly related) error:

```
CudaAPIError                              Traceback (most recent call last)
Python\Python38\lib\site-packages\numba\cuda\cudadrv\driver.py in add_file(self, path, kind)
   2714         try:
-> 2715             driver.cuLinkAddFile(self.handle, kind, pathbuf, 0, None, None)
   2716         except CudaAPIError as e:

Python\Python38\lib\site-packages\numba\cuda\cudadrv\driver.py in safe_cuda_api_call(*args)
    319             retcode = libfn(*args)
--> 320             self._check_ctypes_error(fname, retcode)
    321 

Python\Python38\lib\site-packages\numba\cuda\cudadrv\driver.py in _check_ctypes_error(self, fname, retcode)
    387                 self._detect_fork()
--> 388             raise CudaAPIError(retcode, msg)
    389 

CudaAPIError: [301] Call to cuLinkAddFile results in CUDA_ERROR_FILE_NOT_FOUND

During handling of the above exception, another exception occurred:

LinkerError                               Traceback (most recent call last)
<ipython-input-20-651b6ebdd0e9> in <module>
----> 1 cuda_heat_equation_solver.forall(N + 1)(u_j, u_j1, N*10)

Python\Python38\lib\site-packages\numba\cuda\dispatcher.py in __call__(self, *args)
    436             specialized = self.dispatcher
    437         else:
--> 438             specialized = self.dispatcher.specialize(*args)
    439         blockdim = self._compute_thread_per_block(specialized)
    440         griddim = (self.ntasks + blockdim - 1) // blockdim

Python\Python38\lib\site-packages\numba\cuda\dispatcher.py in specialize(self, *args)
    665         specialization = CUDADispatcher(self.py_func,
    666                                         targetoptions=targetoptions)
--> 667         specialization.compile(argtypes)
    668         specialization.disable_compile()
    669         specialization._specialized = True

Python\Python38\lib\site-packages\numba\cuda\dispatcher.py in compile(self, sig)
    794             kernel = _Kernel(self.py_func, argtypes, **self.targetoptions)
    795             # We call bind to force codegen, so that there is a cubin to cache
--> 796             kernel.bind()
    797             self._cache.save_overload(sig, kernel)
    798 

Python\Python38\lib\site-packages\numba\cuda\dispatcher.py in bind(self)
    176         Force binding to current CUDA context
    177         """
--> 178         self._codelibrary.get_cufunc()
    179 
    180     @property

Python\Python38\lib\site-packages\numba\cuda\codegen.py in get_cufunc(self)
    206             return cufunc
...
-> 2721             raise LinkerError(msg)
   2722 
   2723     def add_cu(self, path, name):

LinkerError: cudadevrt.lib not found
```

I'm on Windows. I've never had any issues running tensorflow/keras with my GPU and CUDA drivers.

**Comment by gmarkall** [comment]
@asaoulis I think cudadevrt.lib was missing from some earlier cudatoolkit packages - this isn't used in a lot of cases, so I can imagine tensorflow and keras working without it. Can you upgrade your driver and toolkit (e.g. to 11.7) to see if that helps? If this doesn't resolve the issue, could you please open a thread on the Discourse group (https://numba.discourse.group/) as that would be a more appropriate place to continue?

**Comment by visualhippocracy** [comment]
hi sorry to bring this topic up but i'm having the same issue, despite having the correct cuda and driver versions.

```
Hardware Information
Machine : AMD64
CPU Name : znver1
CPU Count : 16
Number of accessible CPUs : 16
List of accessible CPUs cores : 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
CFS Restrictions (CPUs worth of runtime) : None

CPU Features : 64bit adx aes avx avx2 bmi bmi2
clflushopt clzero cmov cx16 cx8
f16c fma fsgsbase fxsr lzcnt mmx
movbe mwaitx pclmul popcnt prfchw
rdrnd rdseed sahf sha sse sse2
sse3 sse4.1 sse4.2 sse4a ssse3
xsave xsavec xsaveopt xsaves

Memory Total (MB) : 32720
Memory Available (MB) : 18803

OS Information
Platform Name : Windows-10-10.0.18362-SP0
Platform Release : 10
OS Name : Windows
OS Version : 10.0.18362
OS Specific Version : 10 10.0.18362 SP0 Multiprocessor Free
Libc Version : ?

Python Information
Python Compiler : MSC v.1916 64 bit (AMD64)
Python Implementation : CPython
Python Version : 3.10.9
Python Locale : en_IN.cp1252

Numba Toolchain Versions
Numba Version : 0.56.4
llvmlite Version : 0.39.1

LLVM Information
LLVM Version : 11.1.0

CUDA Information
CUDA Device Initialized : True
CUDA Driver Version : 11.7
CUDA Runtime Version : 11.7
CUDA NVIDIA Bindings Available : False
CUDA NVIDIA Bindings In Use : False
CUDA Detect Output:
Found 1 CUDA devices
id 0 b'NVIDIA GeForce GTX 1080' [SUPPORTED]
Compute Capability: 6.1
PCI Device ID: 0
PCI Bus ID: 12
UUID: GPU-446ba761-7d06-bde9-66d7-10b96089d724
Watchdog: Enabled
Compute Mode: WDDM
FP32/FP64 Performance Ratio: 32
Summary:
1/1 devices are supported

CUDA Libraries Test Output:
Finding nvvm from CUDA_HOME
named nvvm64_40_0.dll
trying to open library... ok
Finding cudart from CUDA_HOME
named cudart64_110.dll
trying to open library... ok
Finding cudadevrt from CUDA_HOME
named cudadevrt.lib
ERROR: failed to find cudadevrt:
cudadevrt.lib not found
Finding libdevice from CUDA_HOME
trying to open library... ok

NumPy Information
NumPy Version : 1.23.5
NumPy Supported SIMD features : ('MMX', 'SSE', 'SSE2', 'SSE3', 'SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2')
NumPy Supported SIMD dispatch : ('SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2', 'AVX512F', 'AVX512CD', 'AVX512_SKX', 'AVX512_CLX', 'AVX512_CNL')
NumPy Supported SIMD baseline : ('SSE', 'SSE2', 'SSE3')
NumPy AVX512_SKX support detected : False

SVML Information
SVML State, config.USING_SVML : True
SVML Library Loaded : True
llvmlite Using SVML Patched LLVM : True
SVML Operational : True

Threading Layer Information
TBB Threading Layer Available : True
+-->TBB imported successfully.
OpenMP Threading Layer Available : True
+-->Vendor: MS
Workqueue Threading Layer Available : True
+-->Workqueue imported successfully.

Numba Environment Variable Information
None found.

Conda Information
Conda Build : 3.24.0
Conda Env : 23.3.1
Conda Platform : win-64
Conda Python Version : 3.10.9.final.0
Conda Root Writable : True
```

**Comment by gmarkall** [comment]
@visualhippocracy This issue already conflates multiple underlying issues, so it's hard to know what issue you're having. Regardless, please start a thread on https://numba.discourse.group with the information above and a description of the issue you're seeing along with any error messages for further help.

**Comment by Empanag** [comment]
Hi, I'm struggling also a little bit with the same issue i work on anaconda environment with python 3.8 my `numba -s `  can anyone help me i 'm trying with the versions but nothing happening.

System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2023-10-31 15:02:20.733859
UTC start time                                : 2023-10-31 13:02:20.733859
Running time (s)                              : 0.638906

__Hardware Information__
Machine                                       : AMD64
CPU Name                                      : znver3
CPU Count                                     : 12
Number of accessible CPUs                     : ?
List of accessible CPUs cores                 : ?
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 64bit adx aes avx avx2 bmi bmi2
                                                clflushopt clwb clzero cmov crc32
                                                cx16 cx8 f16c fma fsgsbase fxsr
                                                invpcid lzcnt mmx movbe mwaitx
                                                pclmul popcnt prfchw rdpid rdrnd
                                                rdseed sahf sha shstk sse sse2
                                                sse3 sse4.1 sse4.2 sse4a ssse3
                                                vaes vpclmulqdq wbnoinvd xsave
                                                xsavec xsaveopt xsaves

Memory Total (MB)                             : 37502
Memory Available (MB)                         : 28553

__OS Information__
Platform Name                                 : Windows-10-10.0.22000-SP0
Platform Release                              : 10
OS Name                                       : Windows
OS Version                                    : 10.0.22000
OS Specific Version                           : 10 10.0.22000 SP0 Multiprocessor Free
Libc Version                                  : ?

__Python Information__
Python Compiler                               : MSC v.1916 64 bit (AMD64)
Python Implementation                         : CPython
Python Version                                : 3.8.18
Python Locale                                 : en_GB.cp1253

__Numba Toolchain Versions__
Numba Version                                 : 0.58.0
llvmlite Version                              : 0.41.0

__LLVM Information__
LLVM Version                                  : 14.0.6

__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : 11.5
CUDA Runtime Version                          : 11.8
CUDA NVIDIA Bindings Available                : False
CUDA NVIDIA Bindings In Use                   : False
CUDA Minor Version Compatibility Available    : False
CUDA Minor Version Compatibility Needed       : True
CUDA Minor Version Compatibility In Use       : False
CUDA Detect Output:
Found 1 CUDA devices
id 0    b'NVIDIA GeForce RTX 2060'                              [SUPPORTED]
                      Compute Capability: 7.5
                           PCI Device ID: 0
                              PCI Bus ID: 1
                                    UUID: GPU-fbd7ec7f-9cc1-393b-5f34-55dd5d81ebaa
                                Watchdog: Enabled
                            Compute Mode: WDDM
             FP32/FP64 Performance Ratio: 32
Summary:
        1/1 devices are supported

CUDA Libraries Test Output:
Finding driver from candidates:
        nvcuda.dll
        \windows\system32\nvcuda.dll
Using loader <class 'ctypes.WinDLL'>
        Trying to load driver...        ok
                Loaded from nvcuda.dll
Finding nvvm from Conda environment
        Located at C:\Users\RSlab12sept2022\anaconda3\envs\Cuda\Library\bin\nvvm64_40_0.dll
        Trying to open library...       ok
Finding nvrtc from Conda environment
        Located at C:\Users\RSlab12sept2022\anaconda3\envs\Cuda\Library\bin\nvrtc64_112_0.dll
        Trying to open library...       ok
Finding cudart from Conda environment
        Located at C:\Users\RSlab12sept2022\anaconda3\envs\Cuda\Library\bin\cudart64_110.dll
        Trying to open library...       ok
Finding cudadevrt from Conda environment
        Located at C:\Users\RSlab12sept2022\anaconda3\envs\Cuda\Library\bin\cudadevrt.lib
        Checking library...     ok
Finding libdevice from Conda environment
        Located at C:\Users\RSlab12sept2022\anaconda3\envs\Cuda\Library\bin\libdevice.10.bc
        Checking library...     ok


__NumPy Information__
NumPy Version                                 : 1.24.3
NumPy Supported SIMD features                 : ('MMX', 'SSE', 'SSE2', 'SSE3', 'SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2')
NumPy Supported SIMD dispatch                 : ('SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2', 'AVX512F', 'AVX512CD', 'AVX512_SKX', 'AVX512_CLX', 'AVX512_CNL', 'AVX512_ICL')
NumPy Supported SIMD baseline                 : ('SSE', 'SSE2', 'SSE3')
NumPy AVX512_SKX support detected             : False

__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : False
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : True
+-->TBB imported successfully.
OpenMP Threading Layer Available              : True
+-->Vendor: MS
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda not available.

__Installed Packages__
Package            Version
------------------ -------
importlib-metadata 6.0.0
llvmlite           0.41.0
mkl-fft            1.3.8
mkl-random         1.2.4
mkl-service        2.4.0
numba              0.58.0
numpy              1.24.3
pip                23.3
setuptools         68.0.0
wheel              0.41.2
zipp               3.11.0

No errors reported.


__Warning log__
Warning: Conda not available.
 Error was [WinError 2] The system cannot find the file specified

Warning (psutil): psutil cannot be imported. For more accuracy, consider installing it.
--------------------------------------------------------------------------------
If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.

=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
=============================================================

**Comment by gmarkall** [comment]
@Empanag You have CUDA driver 11.5 but runtime 11.8 - to make this work you'd need to enable Minor Version Compatibility support, but that is only available on Linux: https://numba.readthedocs.io/en/stable/cuda/minor_version_compatibility.html

You can fix this by:

- Upgrading to a CUDA driver that supports 11.8 or later, or
- Downgrading your CUDA runtime to 11.5 or older.

The relevant info is from this section:

```
__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : 11.5
CUDA Runtime Version                          : 11.8
CUDA NVIDIA Bindings Available                : False
CUDA NVIDIA Bindings In Use                   : False
CUDA Minor Version Compatibility Available    : False
CUDA Minor Version Compatibility Needed       : True
CUDA Minor Version Compatibility In Use       : False
```

(If MVC is needed, it must be available and in use, but it is not available)

**Comment by 2001Iam** [comment]
@gmarkall hello， Now I am getting the error:
`numba.cuda.cudadrv.driver.LinkerError: [222] Call to cuLinkAddData results in CUDA_ERROR_UNSUPPORTED_PTX_VERSION`
ptxas application ptx input, line 9; fatal   : Unsupported .version 8.4; current version is '8.2'
I tried updating numba, but it didn't work. How should I solve this problem
I have run numba -s :

﻿`System info:

__Time Stamp__
Report started (local time)                   : 2025-04-18 10:18:10.367433
UTC start time                                : 2025-04-18 02:18:10.367441
Running time (s)                              : 7.655284
﻿
__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : skylake-avx512
CPU Count                                     : 80
Number of accessible CPUs                     : 32
List of accessible CPUs cores                 : 0-79
CFS Restrictions (CPUs worth of runtime)      : None
﻿
CPU Features                                  : 64bit adx aes avx avx2 avx512bw
                                                avx512cd avx512dq avx512f avx512vl
                                                bmi bmi2 clflushopt clwb cmov
                                                crc32 cx16 cx8 f16c fma fsgsbase
                                                fxsr invpcid lzcnt mmx movbe
                                                pclmul pku popcnt prfchw rdrnd
                                                rdseed rtm sahf sse sse2 sse3
                                                sse4.1 sse4.2 ssse3 xsave xsavec
                                                xsaveopt xsaves
﻿
Memory Total (MB)                             : 128533
Memory Available (MB)                         : 106011
﻿
__OS Information__
Platform Name                                 : Linux-5.15.0-134-generic-x86_64-with-glibc2.17
Platform Release                              : 5.15.0-134-generic
OS Name                                       : Linux
OS Version                                    : #145~20.04.1-Ubuntu SMP Mon Feb 17 13:27:16 UTC 2025
OS Specific Version                           : ?
Libc Version                                  : glibc 2.31
﻿
__Python Information__
Python Compiler                               : GCC 11.2.0
Python Implementation                         : CPython
Python Version                                : 3.8.20
Python Locale                                 : en_US.UTF-8
﻿
__Numba Toolchain Versions__
Numba Version                                 : 0.58.1
llvmlite Version                              : 0.41.1
﻿
__LLVM Information__
LLVM Version                                  : 14.0.6
﻿
__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : 12.2
CUDA Runtime Version                          : 12.4
CUDA NVIDIA Bindings Available                : False
CUDA NVIDIA Bindings In Use                   : False
CUDA Minor Version Compatibility Available    : False
CUDA Minor Version Compatibility Needed       : True
CUDA Minor Version Compatibility In Use       : False
CUDA Detect Output:
Found 3 CUDA devices
id 0     b'NVIDIA RTX A6000'                              [SUPPORTED]
                      Compute Capability: 8.6
                           PCI Device ID: 0
                              PCI Bus ID: 59
                                    UUID: GPU-e0759149-6b47-4f3f-8647-031133dbe1c9
                                Watchdog: Enabled
             FP32/FP64 Performance Ratio: 32
id 1     b'NVIDIA RTX A6000'                              [SUPPORTED]
                      Compute Capability: 8.6
                           PCI Device ID: 0
                              PCI Bus ID: 175
                                    UUID: GPU-3b9efe19-2e0a-ee6d-f1d4-7f0ecc64d5ab
                                Watchdog: Enabled
             FP32/FP64 Performance Ratio: 32
id 2     b'NVIDIA RTX A6000'                              [SUPPORTED]
                      Compute Capability: 8.6
                           PCI Device ID: 0
                              PCI Bus ID: 216
                                    UUID: GPU-93861811-f66b-1139-0d98-c4d7744679c5
                                Watchdog: Enabled
             FP32/FP64 Performance Ratio: 32
Summary:
        3/3 devices are supported
﻿
CUDA Libraries Test Output:
Finding driver from candidates:
        libcuda.so
        libcuda.so.1
        /usr/lib/libcuda.so
        /usr/lib/libcuda.so.1
        /usr/lib64/libcuda.so
        /usr/lib64/libcuda.so.1
Using loader <class 'ctypes.CDLL'>
        Trying to load driver...        ok
                Loaded from libcuda.so
        Mapped libcuda.so paths:
                /usr/lib/x86_64-linux-gnu/libcuda.so.535.230.02
Finding nvvm from System
        Located at /usr/local/cuda/nvvm/lib64/libnvvm.so.4.0.0
        Trying to open library...       ok
Finding nvrtc from System
        Located at /usr/local/cuda/lib64/libnvrtc.so.12.4.127
        Trying to open library...       ok
Finding cudart from System
        Located at /usr/local/cuda/lib64/libcudart.so.12.4.127
        Trying to open library...       ok
Finding cudadevrt from System
        Located at /usr/local/cuda/lib64/libcudadevrt.a
        Checking library...     ok
Finding libdevice from System
        Located at /usr/local/cuda/nvvm/libdevice/libdevice.10.bc
        Checking library...     ok
﻿
﻿
__NumPy Information__
NumPy Version                                 : 1.24.3
NumPy Supported SIMD features                 : ('MMX', 'SSE', 'SSE2', 'SSE3', 'SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2', 'AVX512F', 'AVX512CD', 'AVX512VL', 'AVX512BW', 'AVX512DQ', 'AVX512_SKX')
NumPy Supported SIMD dispatch                 : ('SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2', 'AVX512F', 'AVX512CD', 'AVX512_KNL', 'AVX512_KNM', 'AVX512_SKX', 'AVX512_CLX', 'AVX512_CNL', 'AVX512_ICL')
NumPy Supported SIMD baseline                 : ('SSE', 'SSE2', 'SSE3')
NumPy AVX512_SKX support detected             : True
﻿
__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False
﻿
__Threading Layer Information__
TBB Threading Layer Available                 : True
+-->TBB imported successfully.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.
﻿
__Numba Environment Variable Information__
None found.
﻿
__Conda Information__
Conda Build                                   : not installed
Conda Env                                     : 24.11.1
Conda Platform                                : linux-64
Conda Python Version                          : 3.12.8.final.0
Conda Root Writable                           : False
﻿
__Installed Packages__
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
absl-py                   2.2.1                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aliyun-python-sdk-core    2.16.0                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.5                   pypi_0    pypi
asttokens                 3.0.0                    pypi_0    pypi
attrs                     25.3.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
bev-pool                  0.0.0                     dev_0    <develop>
black                     24.8.0                   pypi_0    pypi
blas                      1.0                         mkl    defaults
blinker                   1.8.2                    pypi_0    pypi
brotli-python             1.0.9            py38h6a678d5_8    defaults
bzip2                     1.0.8                h5eee18b_6    defaults
ca-certificates           2025.2.25            h06a4308_0    defaults
cachetools                5.5.2                    pypi_0    pypi
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1                   pypi_0    pypi
charset-normalizer        3.3.2              pyhd3eb1b0_0    defaults
click                     8.1.8                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
configargparse            1.7                      pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              44.0.2                   pypi_0    pypi
cuda-cudart               12.4.127             h99ab3db_0    defaults
cuda-cudart_linux-64      12.4.127             hd681fbe_0    defaults
cuda-cupti                12.4.127             h6a678d5_1    defaults
cuda-libraries            12.4.1               h06a4308_1    defaults
cuda-nvrtc                12.4.127             h99ab3db_1    defaults
cuda-nvtx                 12.4.127             h6a678d5_1    defaults
cuda-opencl               12.4.127             h6a678d5_0    defaults
cuda-runtime              12.4.1               hb982923_0    defaults
cuda-version              12.4                 hbda6634_3    defaults
cycler                    0.12.1                   pypi_0    pypi
dash                      3.0.1                    pypi_0    pypi
decorator                 5.2.1                    pypi_0    pypi
descartes                 1.1.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.2.0                    pypi_0    pypi
fastjsonschema            2.21.1                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.14.0                   pypi_0    pypi
fire                      0.7.0                    pypi_0    pypi
flake8                    7.1.2                    pypi_0    pypi
flask                     3.0.3                    pypi_0    pypi
fonttools                 4.56.0                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0    defaults
fsspec                    2025.3.0                 pypi_0    pypi
giflib                    5.2.2                h5eee18b_0    defaults
gmp                       6.3.0                h6a678d5_0    defaults
gmpy2                     2.1.2            py38heeb90bb_0    defaults
gnutls                    3.6.15               he1e5248_0    defaults
google-auth               2.38.0                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
grpcio                    1.70.0                   pypi_0    pypi
idna                      3.7              py38h06a4308_0    defaults
imageio                   2.35.1                   pypi_0    pypi
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
importlib-resources       6.4.5                    pypi_0    pypi
iniconfig                 2.1.0                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306    defaults
ipython                   8.12.3                   pypi_0    pypi
ipywidgets                8.1.5                    pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jedi                      0.19.2                   pypi_0    pypi
jinja2                    3.1.4            py38h06a4308_0    defaults
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jpeg                      9e                   h5eee18b_3    defaults
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyterlab-widgets        3.0.13                   pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
lame                      3.100                h7b6447c_0    defaults
lazy-loader               0.4                      pypi_0    pypi
lcms2                     2.16                 hb9589c4_0    defaults
ld_impl_linux-64          2.40                 h12ee557_0    defaults
lerc                      4.0.0                h6a678d5_0    defaults
libcublas                 12.4.5.8             h99ab3db_1    defaults
libcufft                  11.2.1.3             h99ab3db_1    defaults
libcufile                 1.9.1.3              h99ab3db_1    defaults
libcurand                 10.3.5.147           h99ab3db_1    defaults
libcusolver               11.6.1.9             h99ab3db_1    defaults
libcusparse               12.3.1.170           h99ab3db_1    defaults
libdeflate                1.22                 h5eee18b_0    defaults
libffi                    3.4.4                h6a678d5_1    defaults
libgcc                    14.2.0               h767d61c_2    conda-forge
libgcc-ng                 14.2.0               h69a702a_2    conda-forge
libgomp                   14.2.0               h767d61c_2    conda-forge
libiconv                  1.16                 h5eee18b_3    defaults
libidn2                   2.3.4                h5eee18b_0    defaults
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libnpp                    12.2.5.30            h99ab3db_1    defaults
libnvfatbin               12.4.127             h7934f7d_2    defaults
libnvjitlink              12.4.127             h99ab3db_1    defaults
libnvjpeg                 12.3.1.117           h6a678d5_1    defaults
libpng                    1.6.39               h5eee18b_0    defaults
libstdcxx                 14.2.0               h8f9b012_2    conda-forge
libstdcxx-ng              14.2.0               h4852527_2    conda-forge
libtasn1                  4.19.0               h5eee18b_0    defaults
libtiff                   4.5.1                hffd6297_1    defaults
libunistring              0.9.10               h27cfd23_0    defaults
libwebp                   1.3.2                h11a3e52_0    defaults
libwebp-base              1.3.2                h5eee18b_1    defaults
libzlib                   1.2.13               h4ab18f5_6    conda-forge
llvm-openmp               14.0.6               h9e868ea_0    defaults
llvmlite                  0.41.1                   pypi_0    pypi
lyft-dataset-sdk          0.0.8                    pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_1    defaults
markdown                  3.7                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.3            py38h5eee18b_0    defaults
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.1.0         h213fc3f_46344    defaults
mkl-service               2.4.0            py38h5eee18b_1    defaults
mkl_fft                   1.3.8            py38h5eee18b_0    defaults
mkl_random                1.2.4            py38hdb19cb5_0    defaults
mmcv                      2.1.0                    pypi_0    pypi
mmdet                     3.2.0                    pypi_0    pypi
mmdet3d                   1.4.0                    pypi_0    pypi
mmengine                  0.10.7                   pypi_0    pypi
model-index               0.1.11                   pypi_0    pypi
mpc                       1.3.1                h5eee18b_0    defaults
mpfr                      4.2.1                h5eee18b_0    defaults
mpmath                    1.3.0            py38h06a4308_0    defaults
mypy-extensions           1.0.0                    pypi_0    pypi
narwhals                  1.32.0                   pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    defaults
nest-asyncio              1.6.0                    pypi_0    pypi
nettle                    3.7.3                hbbd107a_1    defaults
networkx                  3.1              py38h06a4308_0    defaults
numba                     0.58.1           py38h4144172_0    conda-forge
numpy                     1.24.3           py38hf6e8229_1    defaults
numpy-base                1.24.3           py38h060ed82_1    defaults
nuscenes-devkit           1.1.11                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
ocl-icd                   2.3.2                h5eee18b_1    defaults
open3d                    0.19.0                   pypi_0    pypi
opencv-python             4.11.0.86                pypi_0    pypi
opendatalab               0.0.10                   pypi_0    pypi
openh264                  2.1.1                h4ff587b_0    defaults
openjpeg                  2.5.2                he7f1fd0_0    defaults
openmim                   0.3.9                    pypi_0    pypi
openssl                   3.5.0                h7b32b05_0    conda-forge
openxlab                  0.1.2                    pypi_0    pypi
ordered-set               4.1.0                    pypi_0    pypi
oss2                      2.17.0                   pypi_0    pypi
packaging                 24.2                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pathspec                  0.12.1                   pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.4.0           py38h5eee18b_0    defaults
pip                       24.2             py38h06a4308_0    defaults
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              4.3.6                    pypi_0    pypi
plotly                    6.0.1                    pypi_0    pypi
pluggy                    1.5.0                    pypi_0    pypi
plyfile                   1.0.3                    pypi_0    pypi
prompt-toolkit            3.0.50                   pypi_0    pypi
protobuf                  5.29.4                   pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
pyasn1                    0.6.1                    pypi_0    pypi
pyasn1-modules            0.4.2                    pypi_0    pypi
pycocotools               2.0.7                    pypi_0    pypi
pycodestyle               2.12.1                   pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycryptodome              3.22.0                   pypi_0    pypi
pyflakes                  3.2.0                    pypi_0    pypi
pygments                  2.19.1                   pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pysocks                   1.7.1            py38h06a4308_0    defaults
pytest                    8.3.5                    pypi_0    pypi
python                    3.8.20               he870216_0    defaults
python-dateutil           2.9.0.post0              pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytorch                   2.4.1           py3.8_cuda12.4_cudnn9.1.0_0    pytorch
pytorch-cuda              12.4                 hc786d27_7    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.4                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.2            py38h5eee18b_0    defaults
readline                  8.2                  h5eee18b_0    defaults
referencing               0.35.1                   pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
requests-oauthlib         2.0.0                    pypi_0    pypi
retrying                  1.3.4                    pypi_0    pypi
rich                      13.4.2                   pypi_0    pypi
rpds-py                   0.20.1                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-image              0.21.0                   pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                60.2.0                   pypi_0    pypi
shapely                   1.8.5.post1              pypi_0    pypi
six                       1.17.0                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0    defaults
stack-data                0.6.3                    pypi_0    pypi
sympy                     1.13.3           py38h06a4308_0    defaults
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0    defaults
tensorboard               2.14.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
terminaltables            3.1.10                   pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
tk                        8.6.14               h39e8969_0    defaults
tomli                     2.2.1                    pypi_0    pypi
torchtriton               3.0.0                      py38    pytorch
torchvision               0.20.0               py38_cu124    pytorch
tqdm                      4.65.2                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
trimesh                   4.6.5                    pypi_0    pypi
typing_extensions         4.11.0           py38h06a4308_0    defaults
tzdata                    2025.2                   pypi_0    pypi
urllib3                   1.26.20                  pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
werkzeug                  3.0.6                    pypi_0    pypi
wheel                     0.44.0           py38h06a4308_0    defaults
widgetsnbextension        4.0.13                   pypi_0    pypi
xz                        5.6.4                h5eee18b_1    defaults
yaml                      0.2.5                h7b6447c_0    defaults
yapf                      0.43.0                   pypi_0    pypi
zipp                      3.20.2                   pypi_0    pypi
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.6                hc292b87_0    defaults
﻿
No errors reported.
﻿
﻿
__Warning log__
Warning (psutil): psutil cannot be imported. For more accuracy, consider installing it.

If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.
﻿
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
`

**Comment by erolrecep** [comment]
I solved the issue with this way, in numba docs install page, it says that cuda can be installed with:
$ conda install -c conda-forge cuda-nvcc cuda-nvrtc "cuda-version>=12.0"
however this method looks for available, latest version of the cuda and cuda runtime ones. The better way to set the versions is:
$ conda install -c conda-forge cuda-nvcc cuda-nvrtc "cuda-version==12.8" 
On my setup, I use RTX 2080Ti and compute capability is 7.5 . I installed Cuda 12.8 to my system and it's working without any issue. I decided to install the same version for the numba cuda. Now it fixed the issue.

CUDA Driver Version                           : 12.8
CUDA Runtime Version                          : 12.8

It would be better to change the installation suggestion on numba page.
Thanks!
