### ISSUE TITLE
CUDA on WSL2 Support

### ISSUE THREAD

**Issue by Sahuta** [numba/numba#7104]
---

## Feature request
I just tried to work with CUDA on WSL, with Numba on anaconda 3.
Many part of CUDA features works well, such as nvcc, nvidia-smi,  and python libraries such as Cupy, other than Numba CUDA.

Numba works well while it runs simple @jit compiling.  I add the log when I type `numba -s` bellow.

```
__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : skylake
CPU Count                                     : 8
Number of accessible CPUs                     : 8
List of accessible CPUs cores                 : 0 1 2 3 4 5 6 7
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 64bit adx aes avx avx2 bmi bmi2
                                                clflushopt cmov cx16 cx8 f16c fma
                                                fsgsbase fxsr invpcid lzcnt mmx
                                                movbe pclmul popcnt prfchw rdrnd
                                                rdseed sahf sse sse2 sse3 sse4.1
                                                sse4.2 ssse3 xsave xsavec xsaveopt
                                                xsaves

Memory Total (MB)                             : 24048
Memory Available (MB)                         : 19547

__OS Information__
Platform Name                                 : Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.10
Platform Release                              : 5.10.16.3-microsoft-standard-WSL2
OS Name                                       : Linux
OS Version                                    : #1 SMP Fri Apr 2 22:23:49 UTC 2021
OS Specific Version                           : ?
Libc Version                                  : glibc 2.31

__Python Information__
Python Compiler                               : GCC 7.3.0
Python Implementation                         : CPython
Python Version                                : 3.8.8
Python Locale                                 : ja_JP.UTF-8

__LLVM Information__
LLVM Version                                  : 10.0.1

__CUDA Information__
CUDA Device Initialized                       : False
CUDA Driver Version                           : ?
CUDA Detect Output:
None
CUDA Libraries Test Output:
None

__ROC information__
ROC Available                                 : False
ROC Toolchains                                : None
HSA Agents Count                              : 0
HSA Agents:
None
HSA Discrete GPUs Count                       : 0
HSA Discrete GPUs                             : None

__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : True
+-->TBB imported successfully.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda Build                                   : 3.21.4
Conda Env                                     : 4.10.1
Conda Platform                                : linux-64
Conda Python Version                          : 3.8.8.final.0
Conda Root Writable                           : True

~~~~

__Warning log__
Warning (cuda): CUDA device intialisation problem. Message:Error at driver init:
[100] Call to cuInit results in CUDA_ERROR_NO_DEVICE:
Exception class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>
Warning (roc): Error initialising ROC: No ROC toolchains found.
Warning (roc): No HSA Agents found, encountered exception when searching: Error at driver init:
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_quota_us
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_period_us
<!--

Please include details of the feature you would like to see, why you would
like to see it/the use case.
```

-->

**Comment by gmarkall** [comment]
Generally WSL2 is supported - as CuPy is working, can you give the output of:

```
python -c "from cupy import cupyx; print(cupyx.get_runtime_info())"
```

please?

**Comment by gmarkall** [comment]
Also, what is the output of:

```
python -c "import numba; print(numba.__version__)"
```

**Comment by Sahuta** [comment]
Thank you. 

First, `python -c "from cupy import cupyx; print(cupyx.get_runtime_info())"` just returned `ImportError: cannot import name 'cupyx' from 'cupy'`
Instead I tried `python -c "import cupyx; print(cupyx.get_runtime_i
nfo())"`, then got this;

```
OS                           : Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.10
Python Version               : 3.8.8
CuPy Version                 : 9.1.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.20.2
SciPy Version                : 1.6.2
Cython Build Version         : 0.29.23
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda-11.3
nvcc PATH                    : /usr/local/cuda-11.3/bin/nvcc
CUDA Build Version           : 11030
CUDA Driver Version          : 11040
CUDA Runtime Version         : 11030
cuBLAS Version               : 11501
cuFFT Version                : 10402
cuRAND Version               : 10204
cuSOLVER Version             : (11, 1, 2)
cuSPARSE Version             : 11600
NVRTC Version                : (11, 3)
Thrust Version               : 101100
CUB Build Version            : 101100
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 2070 SUPER
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0
```

**Comment by Sahuta** [comment]
And I checked the versions of numba was `0.53.1` by running your `python -c "import numba; print(numba.__version__)"`.

Thank you for your enthusiastic coping!

**Comment by gmarkall** [comment]
Thanks for the quick reply! One more to check, if you could:

```
python -c "from numba import cuda; cuda.cudadrv.libs.test()"
```

**Comment by gmarkall** [comment]
ah, thanks... in that case, what does:

```
python -c "from numba import cuda; cuda.detect()"
```

give?

**Comment by Sahuta** [comment]
```
Traceback (most recent call last):
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 237, in initialize
    self.cuInit(0)
  File "/home/sota/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/sota/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [100] Call to cuInit results in CUDA_ERROR_NO_DEVICE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sota/anaconda3/lib/python3.8/site-packages/numba/cuda/api.py", line 485, in detect
    print('Found %d CUDA devices' % len(devlist))
  File "/home/sota/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 49, in __len__
    return len(self.lst)
  File "/home/sota/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 26, in __getattr__
    numdev = driver.get_device_count()
  File "/home/sota/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 346, in get_device_count
    self.cuDeviceGetCount(byref(count))
  File "/home/sota/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 280, in __getattr__
    self.initialize()
  File "/home/sota/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 240, in initialize
    raise CudaSupportError("Error at driver init: \n%s:" % e)
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init:
[100] Call to cuInit results in CUDA_ERROR_NO_DEVICE:
```

**Comment by Sahuta** [comment]
```
Traceback (most recent call last):
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 237, in initialize
    self.cuInit(0)
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [100] Call to cuInit results in CUDA_ERROR_NO_DEVICE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/api.py", line 485, in detect
    print('Found %d CUDA devices' % len(devlist))
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 49, in __len__
    return len(self.lst)
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 26, in __getattr__
    numdev = driver.get_device_count()
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 346, in get_device_count
    self.cuDeviceGetCount(byref(count))
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 280, in __getattr__
    self.initialize()
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 240, in initialize
    raise CudaSupportError("Error at driver init: \n%s:" % e)
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init:
[100] Call to cuInit results in CUDA_ERROR_NO_DEVICE:
```

**Comment by gmarkall** [comment]
Thanks - what build of Windows and WSL2 version are you on? There was a previous report of something similar (#6777) that was resolved by an update - are there any updates available for your Windows / WSL2 installation?

**Comment by gmarkall** [comment]
I wonder if this is also relevant (from #6777): https://answers.microsoft.com/en-us/insider/forum/all/version-21327-impacts-nvidia-on-wsl-2/413e96d1-0f62-41de-902e-500fab919427?page=2

**Comment by Sahuta** [comment]
OS is `Microsoft Windows [Version 10.0.21390.1000]`, so I didn't think it was same to v21327's

**Comment by Sahuta** [comment]
There looks nothing to update, by running `wsl --update` returns `No updates are available. Kernel version: 5.10.16`

**Comment by gmarkall** [comment]
Which Linux distro is this? I'd like to install it on a Windows machine to see if I can replicate the issue.

**Comment by gmarkall** [comment]
Also, one other question - it looks like `$CUDA_HOME` is set - what do you get if you unset `$CUDA_HOME` and repeat

```
python -c "from numba import cuda; cuda.cudadrv.libs.test()"
python -c "from numba import cuda; cuda.detect()"
```

?

**Comment by Sahuta** [comment]
It is Ubuntu-20.04

**Comment by gmarkall** [comment]
Thanks - it may take me a little while to try to reproduce.

**Comment by Sahuta** [comment]
Thank you a lot! And while `echo $CUDA_PATH` returns nothing, those 2 python snippets returns exactly the same message.

**Comment by gmarkall** [comment]
Thanks - what about `$CUDA_HOME` though?

**Comment by Sahuta** [comment]
Sorry for typo!
I tried again then got rows like this;
```
(base)  ~      echo $CUDA_HOME                                                                                   

(base)  ~      python -c "from numba import cuda; cuda.cudadrv.libs.test()"                                      
Finding cublas from System
        located at /usr/local/cuda/lib64/libcublas.so.10.2.3.254
        trying to open library...       ok
Finding cusparse from System
        located at /usr/local/cuda/lib64/libcusparse.so.10.3.1.89
        trying to open library...       ok
Finding cufft from System
        located at /usr/local/cuda/lib64/libcufft.so.10.1.2.89
        trying to open library...       ok
Finding curand from System
        located at /usr/local/cuda/lib64/libcurand.so.10.1.2.89
        trying to open library...       ok
Finding nvvm from System
        located at /usr/local/cuda/nvvm/lib64/libnvvm.so.3.3.0
        trying to open library...       ok
Finding cudart from System
        located at /usr/local/cuda/lib64/libcudart.so.10.2.89
        trying to open library...       ok
Finding cudadevrt from System
        located at /usr/local/cuda/lib64/libcudadevrt.a
Finding libdevice from System
        searching for compute_20...     ok
        searching for compute_30...     ok
        searching for compute_35...     ok
        searching for compute_50...     ok
(base)  ~      python -c "from numba import cuda; cuda.detect()"                                                 
Traceback (most recent call last):
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 237, in initialize
    self.cuInit(0)
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [100] Call to cuInit results in CUDA_ERROR_NO_DEVICE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/api.py", line 485, in detect
    print('Found %d CUDA devices' % len(devlist))
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 49, in __len__
    return len(self.lst)
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 26, in __getattr__
    numdev = driver.get_device_count()
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 346, in get_device_count
    self.cuDeviceGetCount(byref(count))
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 280, in __getattr__
    self.initialize()
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 240, in initialize
    raise CudaSupportError("Error at driver init: \n%s:" % e)
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init:
[100] Call to cuInit results in CUDA_ERROR_NO_DEVICE:
```

**Comment by gmarkall** [comment]
What output does executing the following produce:

```python
from ctypes import CDLL, POINTER, byref, c_void_p, c_size_t


# Open the CUDA runtime DLL and create bindings for the cudaMalloc, cudaFree,
# and cudaMemGetInfo functions.

cudart = CDLL('libcudart.so')

cudaMalloc = cudart.cudaMalloc
cudaMalloc.argtypes = [POINTER(c_size_t), c_size_t]

cudaFree = cudart.cudaFree
cudaFree.argtypes = [c_void_p]

cudaMemGetInfo = cudart.cudaMemGetInfo
cudaMemGetInfo.argtypes = [POINTER(c_size_t), POINTER(c_size_t)]


# Python functions for allocation, deallocation, and memory info

def my_alloc(size):
    """
    Allocate `size` bytes of device memory and return a device pointer to the
    allocated memory.
    """
    ptr = c_size_t()
    ret = cudaMalloc(byref(ptr), size)
    if ret:
        raise RuntimeError(f'Unexpected return code {ret} from cudaMalloc')
    return ptr


def my_free(ptr):
    """
    Free device memory pointed to by `ptr`.
    """
    cudaFree(ptr)


def my_memory_info():
    free = c_size_t()
    total = c_size_t()
    cudaMemGetInfo(byref(free), byref(total))
    return free, total

print(my_memory_info())
arr = my_alloc(16384)
print(arr)
print(my_memory_info())
my_free(arr.value)
print(my_memory_info())
```

?

**Comment by Sahuta** [comment]
```
(c_ulong(7501971456), c_ulong(8589934592))
c_ulong(38747963392)
(c_ulong(7499874304), c_ulong(8589934592))
(c_ulong(7501971456), c_ulong(8589934592))
```

**Comment by gmarkall** [comment]
Can you run the script again, but with:

```python
from numba import cuda
cuda.detect()
```

appended please?

**Comment by gmarkall** [comment]
(and paste the output, of course! :-) )

**Comment by Sahuta** [comment]
Got this. Did I went wrong...?

```
(c_ulong(7501971456), c_ulong(8589934592))
c_ulong(38747963392)
(c_ulong(7499874304), c_ulong(8589934592))
(c_ulong(7501971456), c_ulong(8589934592))
Traceback (most recent call last):
  File "/home/sota/cuda/numbachek.py", line 53, in <module>
    from numba import cuda
ModuleNotFoundError: No module named 'numba'

```

**Comment by Sahuta** [comment]
Ah, sorry just a moment

**Comment by Sahuta** [comment]
Got this

```
(c_ulong(7501971456), c_ulong(8589934592))
c_ulong(38747963392)
(c_ulong(7499874304), c_ulong(8589934592))
(c_ulong(7501971456), c_ulong(8589934592))
Traceback (most recent call last):
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 237, in initialize
    self.cuInit(0)
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [100] Call to cuInit results in CUDA_ERROR_NO_DEVICE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "numbachek.py", line 54, in <module>
    cuda.detect()
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/api.py", line 485, in detect
    print('Found %d CUDA devices' % len(devlist))
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 49, in __len__
    return len(self.lst)
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 26, in __getattr__
    numdev = driver.get_device_count()
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 346, in get_device_count
    self.cuDeviceGetCount(byref(count))
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 280, in __getattr__
    self.initialize()
  File "/home/Username/anaconda3/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 240, in initialize
    raise CudaSupportError("Error at driver init: \n%s:" % e)
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init:
[100] Call to cuInit results in CUDA_ERROR_NO_DEVICE:
```

**Comment by gmarkall** [comment]
I suspect there's something wrong with Numba's assumptions about the correct location of libcuda.so on WSL. Let me try making the above example with the driver API to try - will be a few minutes...

**Comment by gmarkall** [comment]
Can you try this one please:

```python
from ctypes import CDLL, POINTER, byref, c_void_p, c_size_t, c_int


cu = CDLL('libcuda.so')

cuInit = cu.cuInit
cuDeviceGet = cu.cuDeviceGet
cuCtxCreate = cu.cuCtxCreate

cuMemAlloc = cu.cuMemAlloc
cuMemAlloc.argtypes = [POINTER(c_size_t), c_size_t]

cuMemFree = cu.cuMemFree
cuMemFree.argtypes = [c_void_p]

cuMemGetInfo = cu.cuMemGetInfo
cuMemGetInfo.argtypes = [POINTER(c_size_t), POINTER(c_size_t)]


# Python functions for allocation, deallocation, and memory info

def my_init():
    ret = cuInit(0)
    if ret:
        raise RuntimeError(f'Unexpected return code {ret} from cuInit')
    dev = c_int()
    ret = cuDeviceGet(byref(dev), 0)
    if ret:
        raise RuntimeError(f'Unexpected return code {ret} from cuDeviceGet')
    ctx = c_void_p()
    ret = cuCtxCreate(byref(ctx), 0, dev)
    if ret:
        raise RuntimeError(f'Unexpected return code {ret} from cuCtxCreate')


def my_alloc(size):
    """
    Allocate `size` bytes of device memory and return a device pointer to the
    allocated memory.
    """
    ptr = c_size_t()
    ret = cuMemAlloc(byref(ptr), size)
    if ret:
        raise RuntimeError(f'Unexpected return code {ret} from cuMemAlloc')
    return ptr


def my_free(ptr):
    """
    Free device memory pointed to by `ptr`.
    """
    cuMemFree(ptr)


def my_memory_info():
    free = c_size_t()
    total = c_size_t()
    cuMemGetInfo(byref(free), byref(total))
    return free, total


my_init()
print(my_memory_info())
arr = my_alloc(16384)
print(arr)
print(my_memory_info())
my_free(arr.value)
print(my_memory_info())


from numba import cuda
cuda.detect()
```

**Comment by Sahuta** [comment]
Thanks a lot!

and your new script returns an error, 
```
Traceback (most recent call last):
  File "numbachek.py", line 62, in <module>
    my_init()
  File "numbachek.py", line 25, in my_init
    raise RuntimeError(f'Unexpected return code {ret} from cuInit')
RuntimeError: Unexpected return code 100 from cuInit
```

**Comment by gmarkall** [comment]
Return code 100 is `CUDA_ERROR_NO_DEVICE`. My suspicion is that we're getting the wrong driver library when we load it explicitly, but the runtime library is able to find the correct one. Can you give the output of running the script from https://github.com/numba/numba/issues/7104#issuecomment-859470459 (the one that uses the runtime API) under GDB and printing out shared libraries like this:

```
echo y | gdb python -ex "break cudaFree" -ex "run numbachek.py" -ex "info shared"
```

please?

**Comment by Sahuta** [comment]
Cool. Thank you again! And GDB prints these message
```
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...
Function "cudaFree" not defined.
Make breakpoint pending on future shared library load? (y or [n]) [answered N; input not from terminal]
Starting program: /home/Username/anaconda3/bin/python numbacheck.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 678]
[New Thread 0x7fffefc8d700 (LWP 679)]
[New Thread 0x7fffed1e5700 (LWP 680)]
(c_ulong(7501971456), c_ulong(8589934592))
c_ulong(38747963392)
(c_ulong(7499874304), c_ulong(8589934592))
(c_ulong(7501971456), c_ulong(8589934592))
[Thread 0x7fffefc8d700 (LWP 679) exited]
[Thread 0x7ffff7c35740 (LWP 674) exited]
[Inferior 1 (process 674) exited normally]
From                To                  Syms Read   Shared Object Library
0x00007ffff7fd0100  0x00007ffff7ff2674  Yes (*)     /lib64/ld-linux-x86-64.so.2
0x00007ffff7f98ae0  0x00007ffff7fa84d5  Yes         /lib/x86_64-linux-gnu/libpthread.so.0
0x00007ffff7dc4630  0x00007ffff7f3920d  Yes         /lib/x86_64-linux-gnu/libc.so.6
--Type <RET> for more, q to quit, c to continue without paging--0x00007ffff7d9a220  0x00007ffff7d9b179  Yes         /lib/x86_64-linux-gnu/libdl.so.2
0x00007ffff7d953e0  0x00007ffff7d95d90  Yes         /lib/x86_64-linux-gnu/libutil.so.1
0x00007ffff7d8c720  0x00007ffff7d8fd70  Yes         /lib/x86_64-linux-gnu/librt.so.1
0x00007ffff7c493c0  0x00007ffff7ceff18  Yes         /lib/x86_64-linux-gnu/libm.so.6
0x00007ffff7fbb040  0x00007ffff7fbd5fc  Yes         /home/Username/anaconda3/lib/python3.8/lib-dynload/_heapq.cpython-38-x86_64-linux-gnu.so
0x00007ffff760e040  0x00007ffff761c86f  Yes         /home/Username/anaconda3/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
0x00007ffff75fc040  0x00007ffff76012fb  Yes (*)     /home/Username/anaconda3/lib/python3.8/lib-dynload/../../libffi.so.7
0x00007ffff75ee040  0x00007ffff75f3232  Yes         /home/Username/anaconda3/lib/python3.8/lib-dynload/_struct.cpython-38-x86_64-linux-gnu.so
0x00007ffff735e840  0x00007ffff73c157c  Yes (*)     /usr/local/cuda-11.3/lib64/libcudart.so
0x00007ffff7125ec0  0x00007ffff7137da4  Yes (*)     /usr/lib/wsl/lib/libcuda.so.1
0x00007ffff708d4d0  0x00007ffff710ce83  Yes (*)     /usr/lib/wsl/lib/libdxcore.so
0x00007ffff5e24e60  0x00007ffff62193c4  Yes (*)     /usr/lib/wsl/drivers/nvhdci.inf_amd64_cfddd2a9238db8a5/libcuda.so.1.1
                                        No          linux-vdso.so.1
```

**Comment by gmarkall** [comment]
Thanks for the info!

Now if you run:

```
NUMBA_CUDA_DRIVER=" /usr/lib/wsl/lib/libcuda.so.1" python numbachek.py
```

what is the output?

**Comment by Sahuta** [comment]
looks goes the same 
```
(c_ulong(7501971456), c_ulong(8589934592))
c_ulong(38747963392)
(c_ulong(7499874304), c_ulong(8589934592))
(c_ulong(7501971456), c_ulong(8589934592))
```

**Comment by Sahuta** [comment]
Appending`from numba import cuda
cuda.detect()`, returns `100`

**Comment by gmarkall** [comment]
Sorry, I made a mistake. I think this would be a better check:

```
NUMBA_CUDA_DRIVER="/usr/lib/wsl/lib/libcuda.so.1" python -c "from numba import cuda; cuda.detect()"
```

Can you try that one please?

**Comment by Sahuta** [comment]
woo!

```
Found 1 CUDA devices
id 0    b'NVIDIA GeForce RTX 2070 SUPER'                              [SUPPORTED]
                      compute capability: 7.5
                           pci device id: 0
                              pci bus id: 1
Summary:
        1/1 devices are supported
```

**Comment by Sahuta** [comment]
So is it need to set as an environmental variable that `NUMBA_CUDA_DRIVER` ??

**Comment by Sahuta** [comment]
Just set, and it works!!

**Comment by gmarkall** [comment]
Yeah, that will be a workaround for now - however, it would be better if Numba were aware of this path on WSL2, so I'll make a PR such that the environment variable will be unnecessary.

Many thanks for your continued help in tracking down the issue!

**Comment by Sahuta** [comment]
Thank you, and it was a great learning about those software, by talking to you.
It's honor to me that my problem to be a improvement of Numba!

**Comment by gmarkall** [comment]
Once I've made the PR I'll let you know, and hopefully you can test it to make sure Numba then works without the environment variable.

ありがとう　ございます！　宜しくお願い致します！

**Comment by gmarkall** [comment]
@sahuta Could you provide me with the output of:

```
ls /usr/lib/wsl/lib/libcuda*
```

please?

**Comment by gmarkall** [comment]
@Sahuta A PR to fix the issue is in https://github.com/numba/numba/pull/7106 - if you're able to check out my branch and build it to test that Numba now works for you on WSL without the need to set the `NUMBA_CUDA_DRIVER` environment variable, I'd really appreciate that!

You should be able to check it out, build, and test it with:

```
conda create -n numbadev python=3.9 numpy=1.19 numba/label/dev::llvmlite scipy jinja2 cffi
conda activate numbadev
git clone git@github.com:gmarkall/numba
cd numba
git checkout wsl-support
python setup.py build_ext --inplace
python -m numba.runtests numba.cuda.tests
```

Could you please let me know how the above goes, and whether Numba seems to be working without the environment variable with that branch please?

**Comment by Sahuta** [comment]
This is the output. Actually I re-installed cuda sometimes. It may cause this issue.
`
/usr/lib/wsl/lib/libcuda.so  /usr/lib/wsl/lib/libcuda.so.1  /usr/lib/wsl/lib/libcuda.so.1.1
`

**Comment by gmarkall** [comment]
Many thanks - it seems like it should be safe for Numba to check for `/usr/lib/wsl/lib/libcuda.so`, as it does in the linked PR.

**Comment by Sahuta** [comment]
I'm trying `git clone git@github.com:gmarkall/numba` but got error. Actually this is the first time I use Github, so may take some time.

**Comment by gmarkall** [comment]
Ah, if it's your first time you won't have an SSH key set up - you should be able to clone it with:

```
git clone https://github.com/gmarkall/numba
```

insead.

**Comment by Sahuta** [comment]
Thank you. I succeeded to clone with the line in last comment, and build goes looks well at the branch. However, cuda_detect() still returns [100] without environmental variable.

**Comment by gmarkall** [comment]
Thanks - just to check it's picking up the right version (in case I made an error in my assumptions about how the above commands would work on your system), can you provide the output of:

```
python -c "import numba; print(numba.__version__)"
```

please?

**Comment by Sahuta** [comment]
It returns `0.15.1+15492.g2fedac64f`

**Comment by gmarkall** [comment]
Thanks - it seems like there's something not quite right about the PR... I have to finish for the day shortly, and will pick this up on Monday - many thanks for your help so far, and apologies for the inconvenience.

**Comment by Sahuta** [comment]
It's no problem ! Numba is awesome, so I'm very pleased to make any contribution.

**Comment by gmarkall** [comment]
I just tried this with Windows 11, Driver 510.06, and Ubuntu 20.04 - building and running Numba master (and running the test suite) seemed to work fine with no issues.

@Sahuta If you install all available updates (Windows updates, NVIDIA driver if it's older than 510.06, WSL kernel (`wsl.exe --update` in a command prompt) and Ubuntu, and Numba), does the issue still occur?

**Comment by gmarkall** [comment]
A hypothesis: Numba looks for `libcuda.so`, then `libcuda.so.1` in that order. If there is a libcuda.so that can be found from a driver installed by a CUDA toolkit, then that might be found ahead of the the `libcuda.so.1` from the driver 510.x needed for CUDA on WSL.

**Comment by maedoc** [comment]
The workaround above (env var pointing to the .so) works on Win 11 WSL2.  Does the PR need some testing to be included?

**Comment by wahyubram82** [comment]
I have the same problem error when importing cudf in python3

the error is:

```
import cudf

Traceback (most recent call last):
  File "cuda/_cuda/ccuda.pyx", line 3556, in cuda._cuda.ccuda._cuInit
RuntimeError: Function "cuInit" not found
Exception ignored in: 'cuda._lib.ccudart.utils.cudaPythonGlobal.lazyInit'
Traceback (most recent call last):
  File "cuda/_cuda/ccuda.pyx", line 3556, in cuda._cuda.ccuda._cuInit
RuntimeError: Function "cuInit" not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bram/miniconda3/lib/python3.8/site-packages/cudf/__init__.py", line 5, in <module>
    validate_setup()
  File "/home/bram/miniconda3/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 60, in validate_setup
    gpus_count = getDeviceCount()
  File "/home/bram/miniconda3/lib/python3.8/site-packages/rmm/_cuda/gpu.py", line 99, in getDeviceCount
    status, count = cudart.cudaGetDeviceCount()
  File "cuda/cudart.pyx", line 8141, in cuda.cudart.cudaGetDeviceCount
  File "cuda/ccudart.pyx", line 486, in cuda.ccudart.cudaGetDeviceCount
  File "cuda/_lib/ccudart/ccudart.pyx", line 1463, in cuda._lib.ccudart.ccudart._cudaGetDeviceCount
  File "cuda/_cuda/ccuda.pyx", line 3583, in cuda._cuda.ccuda._cuDeviceGetCount
RuntimeError: Function "cuDeviceGetCount" not found
```

I already read, all of @gmarkall request to identify the error, so I upload all the result:

cupyx
```
import cupyx
print(cupyx.get_runtime_info())

OS                           : Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.17
Python Version               : 3.8.12
CuPy Version                 : 10.1.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.5
SciPy Version                : 1.8.0
Cython Build Version         : 0.29.27
Cython Runtime Version       : None
CUDA Root                    : /home/bram/miniconda3
nvcc PATH                    : None
CUDA Build Version           : 11020
CUDA Driver Version          : 11060
CUDA Runtime Version         : 11050
cuBLAS Version               : 11704
cuFFT Version                : 10600
cuRAND Version               : 10207
cuSOLVER Version             : (11, 3, 3)
cuSPARSE Version             : 11700
NVRTC Version                : (11, 5)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 6dbba68
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : 21104
NCCL Runtime Version         : 21104
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 3060 Laptop GPU
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:01:00.0
```

numba
```
import numba
from numba import cuda

cuda.detect()

Found 1 CUDA devices
id 0    b'NVIDIA GeForce RTX 3060 Laptop GPU'                              [SUPPORTED]
                      Compute Capability: 8.6
                           PCI Device ID: 0
                              PCI Bus ID: 1
                                    UUID: GPU-98e3eaa0-aeac-b076-67fd-045267d3b3e5
                                Watchdog: Enabled
             FP32/FP64 Performance Ratio: 32
Summary:
        1/1 devices are supported
True
```

`ls /usr/lib/wsl/lib/libcuda*`
result:
`/usr/lib/wsl/lib/libcuda.so  /usr/lib/wsl/lib/libcuda.so.1  /usr/lib/wsl/lib/libcuda.so.1.1`


script:
```
from ctypes import CDLL, POINTER, byref, c_void_p, c_size_t


# Open the CUDA runtime DLL and create bindings for the cudaMalloc, cudaFree,
# and cudaMemGetInfo functions.

cudart = CDLL('libcudart.so')

cudaMalloc = cudart.cudaMalloc
cudaMalloc.argtypes = [POINTER(c_size_t), c_size_t]

cudaFree = cudart.cudaFree
cudaFree.argtypes = [c_void_p]

cudaMemGetInfo = cudart.cudaMemGetInfo
cudaMemGetInfo.argtypes = [POINTER(c_size_t), POINTER(c_size_t)]


# Python functions for allocation, deallocation, and memory info

def my_alloc(size):
    """
    Allocate `size` bytes of device memory and return a device pointer to the
    allocated memory.
    """
    ptr = c_size_t()
    ret = cudaMalloc(byref(ptr), size)
    if ret:
        raise RuntimeError(f'Unexpected return code {ret} from cudaMalloc')
    return ptr


def my_free(ptr):
    """
    Free device memory pointed to by `ptr`.
    """
    cudaFree(ptr)


def my_memory_info():
    free = c_size_t()
    total = c_size_t()
    cudaMemGetInfo(byref(free), byref(total))
    return free, total

print(my_memory_info())
arr = my_alloc(16384)
print(arr)
print(my_memory_info())
my_free(arr.value)
print(my_memory_info())
```

result:
```
(c_ulong(5407899648), c_ulong(6441926656))
c_ulong(21576548352)
(c_ulong(5405802496), c_ulong(6441926656))
(c_ulong(5407899648), c_ulong(6441926656))
```

script 2:
```
from ctypes import CDLL, POINTER, byref, c_void_p, c_size_t, c_int


cu = CDLL('libcuda.so')

cuInit = cu.cuInit
cuDeviceGet = cu.cuDeviceGet
cuCtxCreate = cu.cuCtxCreate

cuMemAlloc = cu.cuMemAlloc
cuMemAlloc.argtypes = [POINTER(c_size_t), c_size_t]

cuMemFree = cu.cuMemFree
cuMemFree.argtypes = [c_void_p]

cuMemGetInfo = cu.cuMemGetInfo
cuMemGetInfo.argtypes = [POINTER(c_size_t), POINTER(c_size_t)]


# Python functions for allocation, deallocation, and memory info

def my_init():
    ret = cuInit(0)
    if ret:
        raise RuntimeError(f'Unexpected return code {ret} from cuInit')
    dev = c_int()
    ret = cuDeviceGet(byref(dev), 0)
    if ret:
        raise RuntimeError(f'Unexpected return code {ret} from cuDeviceGet')
    ctx = c_void_p()
    ret = cuCtxCreate(byref(ctx), 0, dev)
    if ret:
        raise RuntimeError(f'Unexpected return code {ret} from cuCtxCreate')


def my_alloc(size):
    """
    Allocate `size` bytes of device memory and return a device pointer to the
    allocated memory.
    """
    ptr = c_size_t()
    ret = cuMemAlloc(byref(ptr), size)
    if ret:
        raise RuntimeError(f'Unexpected return code {ret} from cuMemAlloc')
    return ptr


def my_free(ptr):
    """
    Free device memory pointed to by `ptr`.
    """
    cuMemFree(ptr)


def my_memory_info():
    free = c_size_t()
    total = c_size_t()
    cuMemGetInfo(byref(free), byref(total))
    return free, total


my_init()
print(my_memory_info())
arr = my_alloc(16384)
print(arr)
print(my_memory_info())
my_free(arr.value)
print(my_memory_info())


from numba import cuda
cuda.detect()
```
result script 2:
```
Traceback (most recent call last):
  File "test_cudf1.py", line 4, in <module>
    cu = CDLL('libcuda.so')
  File "/home/bram/miniconda3/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcuda.so: cannot open shared object file: No such file or directory
```

cuda home / path
`echo $CUDA_HOME`
result
`                                                                                                  `

`echo $CUDA_PATH`
result:
`/home/bram/miniconda3`


cuda
```
import cuda
cuda.cudadrv.libs.test()
```
result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cuda' has no attribute 'cudadrv'
```

Hope all of it can help you identify the cause of my problem...
Please give and advice to fix it.. many thanks before..

**Comment by gmarkall** [comment]
@wahyubram82 This is a bug in the CUDA Python bindings discussed in https://github.com/rapidsai/cudf/issues/10308 - it is being resolved, but in the meantime you may be able to workaround it by setting the environment variable  `LD_LIBRARY_PATH="/usr/lib/wsl/lib/"`

**Comment by wahyubram82** [comment]
> I have the same problem error when importing cudf in python3
> 
> the error is:
> 
> ```
> import cudf
> 
> Traceback (most recent call last):
>   File "cuda/_cuda/ccuda.pyx", line 3556, in cuda._cuda.ccuda._cuInit
> RuntimeError: Function "cuInit" not found
> Exception ignored in: 'cuda._lib.ccudart.utils.cudaPythonGlobal.lazyInit'
> Traceback (most recent call last):
>   File "cuda/_cuda/ccuda.pyx", line 3556, in cuda._cuda.ccuda._cuInit
> RuntimeError: Function "cuInit" not found
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/bram/miniconda3/lib/python3.8/site-packages/cudf/__init__.py", line 5, in <module>
>     validate_setup()
>   File "/home/bram/miniconda3/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 60, in validate_setup
>     gpus_count = getDeviceCount()
>   File "/home/bram/miniconda3/lib/python3.8/site-packages/rmm/_cuda/gpu.py", line 99, in getDeviceCount
>     status, count = cudart.cudaGetDeviceCount()
>   File "cuda/cudart.pyx", line 8141, in cuda.cudart.cudaGetDeviceCount
>   File "cuda/ccudart.pyx", line 486, in cuda.ccudart.cudaGetDeviceCount
>   File "cuda/_lib/ccudart/ccudart.pyx", line 1463, in cuda._lib.ccudart.ccudart._cudaGetDeviceCount
>   File "cuda/_cuda/ccuda.pyx", line 3583, in cuda._cuda.ccuda._cuDeviceGetCount
> RuntimeError: Function "cuDeviceGetCount" not found
> ```
> 
> I already read, all of @gmarkall request to identify the error, so I upload all the result:
> 
> cupyx
> 
> ```
> import cupyx
> print(cupyx.get_runtime_info())
> 
> OS                           : Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.17
> Python Version               : 3.8.12
> CuPy Version                 : 10.1.0
> CuPy Platform                : NVIDIA CUDA
> NumPy Version                : 1.21.5
> SciPy Version                : 1.8.0
> Cython Build Version         : 0.29.27
> Cython Runtime Version       : None
> CUDA Root                    : /home/bram/miniconda3
> nvcc PATH                    : None
> CUDA Build Version           : 11020
> CUDA Driver Version          : 11060
> CUDA Runtime Version         : 11050
> cuBLAS Version               : 11704
> cuFFT Version                : 10600
> cuRAND Version               : 10207
> cuSOLVER Version             : (11, 3, 3)
> cuSPARSE Version             : 11700
> NVRTC Version                : (11, 5)
> Thrust Version               : 101000
> CUB Build Version            : 101000
> Jitify Build Version         : 6dbba68
> cuDNN Build Version          : None
> cuDNN Version                : None
> NCCL Build Version           : 21104
> NCCL Runtime Version         : 21104
> cuTENSOR Version             : None
> cuSPARSELt Build Version     : None
> Device 0 Name                : NVIDIA GeForce RTX 3060 Laptop GPU
> Device 0 Compute Capability  : 86
> Device 0 PCI Bus ID          : 0000:01:00.0
> ```
> 
> numba
> 
> ```
> import numba
> from numba import cuda
> 
> cuda.detect()
> 
> Found 1 CUDA devices
> id 0    b'NVIDIA GeForce RTX 3060 Laptop GPU'                              [SUPPORTED]
>                       Compute Capability: 8.6
>                            PCI Device ID: 0
>                               PCI Bus ID: 1
>                                     UUID: GPU-98e3eaa0-aeac-b076-67fd-045267d3b3e5
>                                 Watchdog: Enabled
>              FP32/FP64 Performance Ratio: 32
> Summary:
>         1/1 devices are supported
> True
> ```
> 
> `ls /usr/lib/wsl/lib/libcuda*` result: `/usr/lib/wsl/lib/libcuda.so /usr/lib/wsl/lib/libcuda.so.1 /usr/lib/wsl/lib/libcuda.so.1.1`
> 
> script:
> 
> ```
> from ctypes import CDLL, POINTER, byref, c_void_p, c_size_t
> 
> 
> # Open the CUDA runtime DLL and create bindings for the cudaMalloc, cudaFree,
> # and cudaMemGetInfo functions.
> 
> cudart = CDLL('libcudart.so')
> 
> cudaMalloc = cudart.cudaMalloc
> cudaMalloc.argtypes = [POINTER(c_size_t), c_size_t]
> 
> cudaFree = cudart.cudaFree
> cudaFree.argtypes = [c_void_p]
> 
> cudaMemGetInfo = cudart.cudaMemGetInfo
> cudaMemGetInfo.argtypes = [POINTER(c_size_t), POINTER(c_size_t)]
> 
> 
> # Python functions for allocation, deallocation, and memory info
> 
> def my_alloc(size):
>     """
>     Allocate `size` bytes of device memory and return a device pointer to the
>     allocated memory.
>     """
>     ptr = c_size_t()
>     ret = cudaMalloc(byref(ptr), size)
>     if ret:
>         raise RuntimeError(f'Unexpected return code {ret} from cudaMalloc')
>     return ptr
> 
> 
> def my_free(ptr):
>     """
>     Free device memory pointed to by `ptr`.
>     """
>     cudaFree(ptr)
> 
> 
> def my_memory_info():
>     free = c_size_t()
>     total = c_size_t()
>     cudaMemGetInfo(byref(free), byref(total))
>     return free, total
> 
> print(my_memory_info())
> arr = my_alloc(16384)
> print(arr)
> print(my_memory_info())
> my_free(arr.value)
> print(my_memory_info())
> ```
> 
> result:
> 
> ```
> (c_ulong(5407899648), c_ulong(6441926656))
> c_ulong(21576548352)
> (c_ulong(5405802496), c_ulong(6441926656))
> (c_ulong(5407899648), c_ulong(6441926656))
> ```
> 
> script 2:
> 
> ```
> from ctypes import CDLL, POINTER, byref, c_void_p, c_size_t, c_int
> 
> 
> cu = CDLL('libcuda.so')
> 
> cuInit = cu.cuInit
> cuDeviceGet = cu.cuDeviceGet
> cuCtxCreate = cu.cuCtxCreate
> 
> cuMemAlloc = cu.cuMemAlloc
> cuMemAlloc.argtypes = [POINTER(c_size_t), c_size_t]
> 
> cuMemFree = cu.cuMemFree
> cuMemFree.argtypes = [c_void_p]
> 
> cuMemGetInfo = cu.cuMemGetInfo
> cuMemGetInfo.argtypes = [POINTER(c_size_t), POINTER(c_size_t)]
> 
> 
> # Python functions for allocation, deallocation, and memory info
> 
> def my_init():
>     ret = cuInit(0)
>     if ret:
>         raise RuntimeError(f'Unexpected return code {ret} from cuInit')
>     dev = c_int()
>     ret = cuDeviceGet(byref(dev), 0)
>     if ret:
>         raise RuntimeError(f'Unexpected return code {ret} from cuDeviceGet')
>     ctx = c_void_p()
>     ret = cuCtxCreate(byref(ctx), 0, dev)
>     if ret:
>         raise RuntimeError(f'Unexpected return code {ret} from cuCtxCreate')
> 
> 
> def my_alloc(size):
>     """
>     Allocate `size` bytes of device memory and return a device pointer to the
>     allocated memory.
>     """
>     ptr = c_size_t()
>     ret = cuMemAlloc(byref(ptr), size)
>     if ret:
>         raise RuntimeError(f'Unexpected return code {ret} from cuMemAlloc')
>     return ptr
> 
> 
> def my_free(ptr):
>     """
>     Free device memory pointed to by `ptr`.
>     """
>     cuMemFree(ptr)
> 
> 
> def my_memory_info():
>     free = c_size_t()
>     total = c_size_t()
>     cuMemGetInfo(byref(free), byref(total))
>     return free, total
> 
> 
> my_init()
> print(my_memory_info())
> arr = my_alloc(16384)
> print(arr)
> print(my_memory_info())
> my_free(arr.value)
> print(my_memory_info())
> 
> 
> from numba import cuda
> cuda.detect()
> ```
> 
> result script 2:
> 
> ```
> Traceback (most recent call last):
>   File "test_cudf1.py", line 4, in <module>
>     cu = CDLL('libcuda.so')
>   File "/home/bram/miniconda3/lib/python3.8/ctypes/__init__.py", line 373, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: libcuda.so: cannot open shared object file: No such file or directory
> ```
> 
> cuda home / path `echo $CUDA_HOME` result ` `
> 
> `echo $CUDA_PATH` result: `/home/bram/miniconda3`
> 
> cuda
> 
> ```
> import cuda
> cuda.cudadrv.libs.test()
> ```
> 
> result:
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: module 'cuda' has no attribute 'cudadrv'
> ```
> 
> Hope all of it can help you identify the cause of my problem... Please give and advice to fix it.. many thanks before..

I have resolve this problem, but another "strange" things happens.

First how I resolve this:
I use:
`sudo update-alternatives --config python3`
the choose python3 from:
`/home/user/miniconda3/bin/python3`

If I work my script in wsl, I mean, I type: `wsl`
then after that do all operation from linux wsl it's works fine.
all going perfect...

but after I made a script with `import cudf` and try to run in from windows with: `wsl myscript.py` that contains `import cudf`, the error show up again, `RuntimeError: Function "cuDeviceGetCount" not found`.

I try similar method to setting all environment like  I do in wsl active condition by using command `wsl setting_order` run from command prompt windows environtment. including set the `update-alternatives --config python3` to `/home/user/miniconda3/bin/python3`.

with this condition may be @gmarkall have a clue what happened...

**Comment by LunaCelestine** [comment]
Any updates on this? It seems like WSL2 is actually becoming a reasonably solid dev platform and I'd love to get this working.

**Comment by gmarkall** [comment]
Closing this issue as WSL2 is fully supported, and the issues discussed in this thread only manifest when there are mixed-up versions of libcuda.so installed (e.g. from the preview driver and installed with a CUDA toolkit installer).

**Comment by gmarkall** [comment]
> Setting the environmental variable is proven to be useful even as of today! (With the latest WSL2)

If that happens, you probably have a non-WSL2 driver installed in your WSL2 environment. You probably have a `libnvidia-compute-xxx` package installed - see the discussion on https://github.com/numba/numba/issues/9032 for how to check and remove the offending package.
