### ISSUE TITLE
Call to cuInit results in UNKNOWN_CUDA_ERROR

### ISSUE THREAD

**Issue by FindHao** [numba/numba#8985]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hi, I got an error when use numba.cuda to get GPU information. The GPU is NVIDIA A100. Actually, I got the exact same error on another A100 server too. But the GPU works well on CUDA applications like pytorch. The GPU driver version is 525.85.12.

Could you help me figure out what happened? 

```
>>> from numba import cuda
>>> cuda.gpus
<numba.cuda.cudadrv.devices._DeviceList object at 0x7ff235c73910>
>>> for gpu in cuda.gpus:
...   print(gpu)
... 
Traceback (most recent call last):
  File "/home/users/a/miniconda3/envs/pt_may23_compiled/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 267, in ensure_initialized
    self.cuInit(0)
  File "/home/users/a/miniconda3/envs/pt_may23_compiled/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 340, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "/home/users/a/miniconda3/envs/pt_may23_compiled/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 408, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [34] Call to cuInit results in UNKNOWN_CUDA_ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/a/miniconda3/envs/pt_may23_compiled/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 46, in __iter__
    return iter(self.lst)
  File "/home/users/a/miniconda3/envs/pt_may23_compiled/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 26, in __getattr__
    numdev = driver.get_device_count()
  File "/home/users/a/miniconda3/envs/pt_may23_compiled/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 437, in get_device_count
    self.cuDeviceGetCount(byref(count))
  File "/home/users/a/miniconda3/envs/pt_may23_compiled/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 305, in __getattr__
    self.ensure_initialized()
  File "/home/users/a/miniconda3/envs/pt_may23_compiled/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 271, in ensure_initialized
    raise CudaSupportError(f"Error at driver init: {description}")
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: Call to cuInit results in UNKNOWN_CUDA_ERROR (34)

```
Part of the output of `numba -s`:
```
__OS Information__
Platform Name                                 : Linux-4.18.0-372.26.1.el8_6.x86_64-x86_64-with-glibc2.28
Platform Release                              : 4.18.0-372.26.1.el8_6.x86_64
OS Name                                       : Linux
OS Specific Version                           : ?
Libc Version                                  : glibc 2.28

__Python Information__
Python Compiler                               : GCC 11.2.0
Python Implementation                         : CPython
Python Version                                : 3.10.11
Python Locale                                 : en_US.UTF-8

__Numba Toolchain Versions__
Numba Version                                 : 0.57.0
llvmlite Version                              : 0.40.0

__LLVM Information__
LLVM Version                                  : 14.0.6

__CUDA Information__
CUDA Device Initialized                       : False
CUDA Driver Version                           : ?
CUDA Runtime Version                          : ?
CUDA NVIDIA Bindings Available                : ?
CUDA NVIDIA Bindings In Use                   : ?
CUDA Minor Version Compatibility Available    : ?
CUDA Minor Version Compatibility Needed       : ?
CUDA Minor Version Compatibility In Use       : ?
CUDA Detect Output:
None
CUDA Libraries Test Output:
None

```

**Comment by FindHao** [comment]
BTW, I can use `pynvml` to list all GPUs successfully.

**Comment by gmarkall** [comment]
> Could you help me figure out what happened?

I hope so! Could you provide the output of:

```
conda list
```

```
python -c "from numba import cuda; cuda.cudadrv.libs.test()"
```

```
yum list installed | grep nvidia
```

and

```
yum list installed | grep cuda
```

please? (The last two I'm not 100% certain of the yum command as I don't normally use CentOS - usually I'd ask a user to run `dpkg --get-selections` on a Debian-based distro, and that's what I'm trying to suggest the equivalent of here)

**Comment by FindHao** [comment]
```
% conda list
# packages in environment at /home/users/a/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
boltons                   23.0.0          py310h06a4308_0  
brotlipy                  0.7.0           py310h7f8727e_1002  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.01.10           h06a4308_0  
certifi                   2022.12.7       py310h06a4308_0  
cffi                      1.15.1          py310h5eee18b_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
conda                     23.3.1          py310h06a4308_0  
conda-content-trust       0.1.3           py310h06a4308_0  
conda-package-handling    2.0.2           py310h06a4308_0  
conda-package-streaming   0.7.0           py310h06a4308_0  
cryptography              39.0.1          py310h9ce1e76_0  
idna                      3.4             py310h06a4308_0  
jsonpatch                 1.32               pyhd3eb1b0_0  
jsonpointer               2.1                pyhd3eb1b0_0  
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
llvmlite                  0.40.0                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
numba                     0.57.0                   pypi_0    pypi
numpy                     1.24.3                   pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0  
packaging                 23.0            py310h06a4308_0  
pip                       23.0.1          py310h06a4308_0  
pluggy                    1.0.0           py310h06a4308_1  
pycosat                   0.6.4           py310h5eee18b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 23.0.0          py310h06a4308_0  
pysocks                   1.7.1           py310h06a4308_0  
python                    3.10.10              h7a1cb2a_2  
readline                  8.2                  h5eee18b_0  
requests                  2.28.1          py310h06a4308_1  
ruamel.yaml               0.17.21         py310h5eee18b_0  
ruamel.yaml.clib          0.2.6           py310h5eee18b_1  
setuptools                65.6.3          py310h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.1               h5eee18b_0  
tk                        8.6.12               h1ccaba5_0  
toolz                     0.12.0          py310h06a4308_0  
tqdm                      4.65.0          py310h2f386ee_0  
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.15         py310h06a4308_0  
wheel                     0.38.4          py310h06a4308_0  
xz                        5.2.10               h5eee18b_1  
zlib                      1.2.13               h5eee18b_0  
zstandard                 0.19.0          py310h5eee18b_0  
```
```
% python -c "from numba import cuda; cuda.cudadrv.libs.test()"
Finding driver from candidates: libcuda.so, libcuda.so.1, /usr/lib/libcuda.so, /usr/lib/libcuda.so.1, /usr/lib64/libcuda.so, /usr/lib64/libcuda.so.1...
Using loader <class 'ctypes.CDLL'>
	trying to load driver...	ok, loaded from libcuda.so
Finding nvvm from CUDA_HOME
	located at /scratch/yhao24/opt/cuda-12.1/nvvm/lib64/libnvvm.so.4.0.0
	trying to open library...	ok
Finding cudart from CUDA_HOME
	located at /scratch/yhao24/opt/cuda-12.1/lib64/libcudart.so.12.1.55
	trying to open library...	ok
Finding cudadevrt from CUDA_HOME
	located at /scratch/yhao24/opt/cuda-12.1/lib64/libcudadevrt.a
Finding libdevice from CUDA_HOME
	trying to open library...	ok
```
```
yum list installed | grep nvidia

libnvidia-container-tools.x86_64                    1.12.0-1                                                      @libnvidia-container                       
libnvidia-container1.x86_64                         1.12.0-1                                                      @libnvidia-container                       
nvidia-container-toolkit.x86_64                     1.12.0-1                                                      @libnvidia-container                       
nvidia-container-toolkit-base.x86_64                1.12.0-1                                                      @libnvidia-container                       
nvidia-docker2.noarch                               2.11.0-1                                                      @libnvidia-container                       
pcp-pmda-nvidia-gpu.x86_64                          5.3.7-7.el8                                                   @rhel-8-for-x86_64-appstream-rpms      
```
```
% yum list installed | grep cuda


```
I use the cudatoolkit installed by myself.

**Comment by gmarkall** [comment]
Many thanks - can you now run

```
python -c "from ctypes import CDLL; CDLL('libcuda.so')._undef"
```

and paste the output please? (This is intended to reveal the location of `libcuda.so` that was loaded when it was located without a specified path)

**Comment by FindHao** [comment]
```
python -c "from ctypes import CDLL; CDLL('libcuda.so')._undef"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/users/a/miniconda3/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/home/users/a/miniconda3/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /scratch/yhao24/opt/cuda-12.1/lib64/stubs/libcuda.so: undefined symbol: _undef
```

**Comment by gmarkall** [comment]
Is that path `/scratch/yhao24/opt/cuda-12.1/lib64/stubs` somewhere on your `LD_LIBRARY_PATH` or something? The stub library it's loading is intended to allow you to link against libcuda.so on a system that doesn't have the driver installed, and it doesn't have any actual implementations. Usually I would expect to find it in `/lib/x86_64-linux-gnu/libcuda.so` on an Ubuntu system, but I don't know where it should be on CentOS.

Does this provide you with enough information to modify your system configuration such that the "real" `libcuda.so` is located by ld ahead of the stub?

**Comment by FindHao** [comment]
Somehow, I added `$CUDA_PATH/lib64/stubs` to `LD_LIBRARY_PATH`. I can't remember the exact reason.  
After I reset it, numba.cuda works! Thanks for your help!

**Comment by gmarkall** [comment]
Glad it works now! Are you happy to close this issue?
